### PR TITLE
Apply for adding new json schema validator implementation for .Net: LateApexEarlySpeed.Json.Schema

### PR DESCRIPTION
**Pull request by lateapexearlyspeed**
Hello, recently I created my personal project about json schema implementation for .net. It is based on draft 2020-12, has known limitation currently listed in project doc but it also has some features and advantages. Currently it is a free close source project and may be transferred to be open source in future.

I am not sure if it is proper to be added to this website's implementation list. The description of implementation: https://github.com/lateapexearlyspeed/Lateapexearlyspeed.JsonSchema.Doc

Intention of writing this implementation:
Several years ago, I touched and learned json schema concept during work, and feel json schema is interesting concept because it can describe any data well, and I used some excellent json schema libraries for work. Years later, I would like to implement json schema myself and meantime try to find some difficulties so to improve my develop skills during design and coding, performance optimization and CICD experience for this project. Now I would also hope more people can use it.

Thanks !

### CODE REVIEW

**Review by benjagm — APPROVED** [review]
Looks good to me! 

Thanks a lot for adding your .NET implementation! Great job!

**Review by Relequestual — APPROVED** [review]
Thanks for your contribution.

**Comment by benjagm** [comment]
We just promoted your implementation in social media: 
- https://www.linkedin.com/feed/update/urn:li:activity:7150480202270154754
- https://x.com/jsonschema/status/1744714093641253156?s=20

**Comment by lateapexearlyspeed** [comment]
Thanks, it is my pleasure to add this implementation :)

**Pull request merged**
