### PR TITLE
Fix: Getting back the lost changes from PR  #365

### LINKED ISSUE #528: 🐛 Bug: Getting the lost changes from the merger of dark theme pr.
### Describe the bug

After merging the dark theme PR #365 several changes previous done are now lost which should be recovered.

As of now the dark them is rolled back from the production in is placed in the new branch `web-dark-theme` , this branch needs to be compared with the `main` ( production branch ) to revoer the changes back.

### Steps To Reproduce

N/A

### Expected Behavior

The previous changes should be recovered while also implementing back the dark theme.

### Screenshots

N/A

### Device Information [optional]

```markdown
- OS: Linux (Debian)
- Browser: Firefox
- version: latest
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
**What kind of change does this PR introduce?**

Getting back the lost changes from the pr #365 

Fixed landing page, blog page, implementations page, blog markdown file and components for documentation page 

**Issue Number:**

-  Closes #528 

**If relevant, did you update the documentation?**
N/A

**Summary**
Lost changes from previous PRs are now back

**Does this PR introduce a breaking change?**
N/A

### CODE REVIEW

**Comment by utnim2** [comment]
LGTM !

**Comment by benjagm** [comment]
Hi @DhairyaMajmudar !  Thanks a lot for the huge effort with this!!

Everything looks great! The only thing I found is I think we have lost this change: https://github.com/json-schema-org/website/pull/359

**Comment by DhairyaMajmudar** [comment]
Yes I have done that changes again : )

**Comment by benjagm** [comment]
Thanks Dhairya. We have lost #503 too. Can you please fix that one and rebase?

**Comment by DhairyaMajmudar** [comment]
I have rebased the PR as of #503 there are no changes with the files included with them even though the scroll to top button is not visible.

**Pull request merged**
