### PR TITLE
Link-Redirect-Fix

### PR DESCRIPTION
**Pull request by Yashwanth1906**
What kind of change does this PR introduce?
Change to correct wrong redirecting URLs
Issue Number:
closes: https://github.com/json-schema-org/website/issues/1038

Screenshots/videos:

If relevant, did you update the documentation?

Summary

This pull request addresses an issue related to incorrect URL redirection in the JSON Schema website. Users were being redirected to incorrect or unintended pages when clicking on certain links.

Changes Made:
Corrected Redirecting URLs: Updated the wrong redirecting URLs in various components to ensure they point to the correct destinations. This change enhances navigation and provides users with access to the intended content.

Refactored JSX Components: Adjusted the formatting of JSX components to comply with the project's style guide. Specifically, I ensured that there were proper spaces before closing brackets in the JSX tags, addressing the errors raised by the reviewers.

Code Consistency: Ensured consistency in the codebase by adhering to Prettier and ESLint rules, which included correcting formatting issues to enhance code readability and maintainability.

These changes improve user experience by ensuring that links function correctly, reducing frustration caused by misdirected navigation.

Does this PR introduce a breaking change?

No

### CODE REVIEW

**Comment by DarhkVoyd** [comment]
I believe using the suggested TypeScript version will resolve the issue.

**Comment by Yashwanth1906** [comment]
@DarhkVoyd  Can i change the typescript version? It will lead to unauthorized access.

**Comment by Yashwanth1906** [comment]
@DarhkVoyd  Is this pull request is merged or closed. Do i need to fix this one or not?

**Comment by DarhkVoyd** [comment]
@Yashwanth1906 I meant the TypeScript version for your local development environment to match the requirments of the codebase. There is nothing to be merged, you force pushed to this PR and closed it.

**Pull request closed without merging**
