### PR TITLE
Fixed Community Link navigation

### LINKED ISSUE #402: Top menu - Community link navigation is sub-optimal
#### Describe the bug
When in the landing page, if I click in community that is a section in the same page, the content location is suboptimal when we expect the title of the community section appearing on top. See image.

Current:
Screenshot 2024-03-01 at 13 46 57

Desired:
Screenshot 2024-03-01 at 13 50 29

### PR DESCRIPTION
**Pull request by TamannaVerma99**
**GitHub Issue:** #402 
Resolves #402 

**Summary**:
The issue with the community link navigation has been resolved by adjusting the CSS within the relevant section. 
**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

P.S :
This bug may occur across multiple interfaces due to in-page navigation, so I believe that a minor refactor of the codebase can prevent all such occurences in the future.
The suggested refactor involves creating separate components for each distinct section of the page and then organizing them through routes on a landing page. This approach not only permanently resolves the navigation issue but also helps mitigate the lag experienced while navigating between different parts of the page.

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
Thanks for the PR 

LGTM!

**Comment by DhairyaMajmudar** [comment]
LGTM!

**Review by benjagm — APPROVED** [review]
Good job!! Approved from side.

**Comment by TamannaVerma99** [comment]
Thanks!

**Pull request merged**
