### PR TITLE
Bug/Maintenance: Updating actions to use Node.js 20

### LINKED ISSUE #539: 🐛Bug/Maintenance: Updating actions to use Node.js 20
### Describe the bug

Two of the Github Action workflows in our repo are using Node.js-16 and Node.js-12 based actions which are deprecated:
- New Implementation Commenter , uses actions/github-script@v6
Screenshot 2024-03-14 021805

- Greet on User First PR Merge, uses actions/github-script@v4
greet on first merge
It would be great if for these two workflows, we can update the actions/github-script to v7, which is the latest version based on Node.js 20. (for reference: [github-script releases](https://github.com/actions/github-script/releases))

### Steps To Reproduce

The warnings can be seen in the Actions tab of the repo, going to latest run of these workflows.

### Expected Behavior

actions/github-script must be upgraded to v7, the latest version based on Node 20 which will remove the warnings shown by Github.

### Screenshots

_No response_

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

### PR DESCRIPTION
**Pull request by ayushtiwari110**
**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #539  

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**
- Updated the actions/github-script to v7 , which is the latest version using Node.js 20.

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by ayushtiwari110** [comment]
Hi @benjagm , I guess the workflows are not configured for manual triggering from the actions tab. They'll get triggered only for their specific event. So there wasn't option for manually executing them in my fork

**Comment by ayushtiwari110** [comment]
Hi @benjagm , kindly have a look at my previous comment, and do share the further plan of action. Thanks!

**Review by benjagm — APPROVED** [review]

**Comment by benjagm** [comment]
Great job! Let's merge it!

**Comment by ayushtiwari110** [comment]
Thanks!

**Pull request merged**
