### PR TITLE
Enhancement: use env vars instead of hardcoded credentials

### LINKED ISSUE #514: ✨ Enhancement: Api keys and other secrets should be loaded in env instead of hardcoding them in source
### Is your feature request related to a problem? Please describe

Not necessarily but i think it can result into a problem as it's not a good practice i presume for apiKeys or any keys to remain out int the open.

### Describe the solution you'd like

to use dotenv package to load them from an env file

### Describe alternatives you've considered

using env files to store such variables 
and use dotenv to load them

### Additional context

_No response_

### Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by maverox**
**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #514 
-  Related to #___ 
-  Others? 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Comment by benjagm** [comment]
We are going to put this PR on hold until have a correct way to manage secrets in cloudflare

**Review by aialok — APPROVED** [review]
Looks good to me.
 I'll create an issue regarding the updating of documentation about this.

**Comment by maverox** [comment]
Really means a lot.
By the way should I resolve the conflict shown here as well?

**Comment by aialok** [comment]
> Really means a lot. By the way should I resolve the conflict shown here as well?

Yes, Please : )

**Review by benjagm — APPROVED** [review]
Amazing job. I just resolved the conflicts to merge this.

**Pull request merged**
