### PR TITLE
Updating carbonads location to upper right

### PR DESCRIPTION
**Pull request by benjagm**
Updating carbonads location to upper right like it was in the old website.

Related: #63

### CODE REVIEW

**Comment by benjagm** [comment]
> We probably want something like the example "Paragraph + mobile breakpoint" shows.

IMHO Providing that space above the main content to carbon ads we are providing so much top-quality space to just advertising and you suggesting that made me wonder: What do we want from showing Ads? What is the benefit? Is our goal just put the ads in the best space to monetize? Is our goal having a way to get funds without scarifying the best space for users content?

**Comment by Relequestual** [comment]
> What do we want from showing Ads? What is the benefit? Is our goal just put the ads in the best space to monetize? Is our goal having a way to get funds without sacrifying the best space for educating json schema users?

Well, it is useful to have funds, but we don't want to get in the way of users either.

Given the Carbon ads site shows a number of popular projects as examples, I decided to take a look at what they do.

Bootstrap: 
- On home page
- Docs pages: After header and intro
- Blog pages: Under sidebar on desktop. After header and intro on mobile

Laravel:
- Fixed right bottom corner on when space. Never overlaps content. If would overlap content, shown at the end of content.

Vue:
- Bottom of right side bar, if space, under sponsors, which is under "on this page"

Eslint: 
- On home page
- Docs pages: Right sidebar before table of contense for desktop. ToC moves to under header on "tablet" size, leaving just the ad. No ads on mobile.
- Blog pages: No ads

Fixing it at the bottom right is probably fine, as long as soon as it would overlap content, it moves elsewhere, or is removed. (For docs)

For the blog pages, I think it needs to be fixed at the bottom of the left sidebar, making sure that it never covers up the ToC. Or, we could remove them from the blog altogether. It's not a large portion of the traffic to be honest.

**Comment by benjagm** [comment]
@Relequestual Can you please take a look of the proposal of this PR?
Docs: https://0591006f.website-2v2.pages.dev/learn/getting-started-step-by-step
Blog: https://0591006f.website-2v2.pages.dev/blog/posts/new-website

**Comment by benjagm** [comment]
hey @Relequestual Can we merge this?

**Review by Relequestual — CHANGES_REQUESTED** [review]
Per comment above

**Comment by benjagm** [comment]
I'll close this PR for now.

**Pull request closed without merging**
