### PR TITLE
fix: next.js cache issue

### LINKED ISSUE #1178: 🐛 Bug: Remove Next.js build cache from preview.yml.
### Describe the bug

- We are facing an issue with the Next.js build cache, which we are using for preview deployments. Due to this, CSS changes are not being updated as expected, and the older cache from the previous builds is causing the problem.

- Removing the cache step will fix the issue.

Discussion : https://json-schema.slack.com/archives/C8C4UBXDF/p1734423225071989?thread_ts=1734410032.558099&cid=C8C4UBXDF

### Steps To Reproduce

1. Create a PR.  
2. After that, push a commit to the PR with the CSS changes.  

### Expected Behavior

- It should work as expected.

### Screenshots

_No response_

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

### PR DESCRIPTION
**Pull request by saurabhraghuvanshii**
**What kind of change does this PR introduce?**

bug #1178  it clear Next.js cache in order to keep new css changes .

**Issue Number:**
-  Closes #1178 

**Summary**
close #1178  remove cache to show latest change to css
**Does this PR introduce a breaking change?**
no

### CODE REVIEW

**Comment by aialok** [comment]
image

hey, I think you misunderstood the issue. you just need to remove the above steps.
Thanks for the PR

**Comment by saurabhraghuvanshii** [comment]
@aialok  check sir is this ok!

**Review by aialok — APPROVED** [review]
LGTM :rocket: 
Thanks @saurabhraghuvanshii

**Comment by saurabhraghuvanshii** [comment]
@aialok thanks you sir for your  guidance

**Pull request merged**
