### PR TITLE
🔧 Fix: SVG Loading Issues in Dark Mode for Case Studies

### LINKED ISSUE #850: 🐛 Bug: Some SVG images are not loading correctly in dark mode on the case studies page.
### Describe the bug

- Some SVG images are not loading in correct theme in dark mode on the case studies page.
-  https://json-schema.org/overview/case-studies

### Steps To Reproduce

- Visit https://json-schema.org/overview/case-studies

### Expected Behavior

- It should render correctly in both light and dark mode.

### Screenshots

[Screencast from 2024-08-05 18-22-17.webm](https://github.com/user-attachments/assets/bee636ff-5bd1-4bcb-ad6b-c520de119ca4)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

### PR DESCRIPTION
**Pull request by Michael-Obele**
**What kind of change does this PR introduce?**

- Fix

**Issue Number:**
- Closes #850

**Screenshots/videos:**

Case Studies Dark Mode

Case Studies Light Mode

**If relevant, did you update the documentation?**

Documentation updated to reflect changes in theme handling for images.

**Summary**

This pull request addresses the issue where some SVG images were not loading correctly in dark mode on the case studies page. By implementing theme-based image URLs, the images will now render correctly in both light and dark modes, improving the overall user experience. This change resolves the bug reported in issue #850.

**Does this PR introduce a breaking change?**

No, this PR does not introduce any breaking changes. Existing functionality remains intact, and the new image handling is backward compatible.

### CODE REVIEW

**Review by DhairyaMajmudar — COMMENTED** [review]
Pls. change the logo image file to `svg` and rename it `github-logo-white.svg`

**Comment by Michael-Obele** [comment]
> Pls. change the logo image file to `svg` and rename it `github-logo-white.svg`

Done

**Review by DhairyaMajmudar — APPROVED** [review]
Thank you for amazing PR, looks good to me 🚀

**Comment by Michael-Obele** [comment]
Great, please, @benjagm; we'd love for you to check it out.

**Review by benjagm — APPROVED** [review]
Great work!! Much appreciated!!

**Pull request merged**
