### PR TITLE
Added the link and steps for API Key from Agolia while Setting Up Environment

### LINKED ISSUE #989: [📝 Docs]: Improvement in installation instructions
### What Docs changes are you proposing?

I would like to contribute to `INSTALLATION.md` by improving the installation instructions.
The installation guide is great but it could be better. 
Some things that I think can be clarified or added are :

- Adding step mentioning to fork the repo.
- Add the `git clone ` command/instruction before the `git submodule init`
- Give the link to [Algolia](https://www.algolia.com/) to sign up and get credentials for the `env`.
- Since the Algolia dashboard has two types of API keys which are `Admin API Key` and `Search API Key` we can mention that the contributor needs to get the `Search API Key`.

I want to understand if these changes are worth making. If they are, I would like to work on this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by swastikCommits**
**What kind of change does this PR introduce?**

Fixes the INSTALLATION.md where a link was attached to Agolia for application ID and Search API Key  foe setting up the environment variables.

**Issue Number:**

-  Closes #989  

**Screenshots/videos:**

**If relevant, did you update the documentation?**

Yes

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by swastikCommits** [comment]
Maintainers please review it.
@DhairyaMajmudar

**Comment by swastikCommits** [comment]
@DhairyaMajmudar Can you let me know why isnt the PR being accepted, it is blocked. I am new to Open Source Community.

**Comment by DhairyaMajmudar** [comment]
@swastikCommits patience, some things go fast, some not, in open source many factors can influence merge of a given PR and delay things

**Comment by DhairyaMajmudar** [comment]
Changes are related to docs, @valeriahhdez can you pls. help in review

**Comment by swastikCommits** [comment]
> @swastikCommits patience, some things go fast, some not, in open source many factors can influence merge of a given PR and delay things

Thanks for the response, my bad I thought that there must be some issues in my commit or the tests might have beeb declined.

**Comment by benjagm** [comment]
@kwennB @valeriahhdez and @AnithaKraman. Please check.

Please note that this step is not necessary at all for a local setup; it is only necessary for production, so this is what we need to clarify. The second thing we need to clarify is we are not using the Algolia product, instead, we are using DocSearch, which is totally free https://docsearch.algolia.com/

**Comment by benjagm** [comment]
Thanks for your contribution.  

For the [reasons](https://github.com/json-schema-org/website/issues/989#issuecomment-2463842610) explained in the issue, we decided to close this PR in favour of a different explanation of that step, that is optional for a local setup.

**Pull request closed without merging**
