### PR TITLE
Bug:ambassadors Page

### LINKED ISSUE #1160: 🐛 Bug: Padding of button in Become a JSON Schema Ambassador (Mobile view)
### Describe the bug

Everything is fine up to the tablet view, but in the mobile view, the "Become Ambassador" text is spilling out of the button. We need to adjust the padding to fix this.

### Steps To Reproduce

1.Go to the mobile view of the page.
2.Locate the "Become Ambassador" button.
3.Observe how the text overflows or spills out of the button.

### Expected Behavior

The "Become Ambassador" text should remain properly contained within the button, with appropriate padding and alignment for a clean and responsive design.

### Screenshots

json

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

### PR DESCRIPTION
**Pull request by Pavankumar07s**
**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #1160 1160_ 
-  Related to #1160___ 
-  Others? 

**Screenshots/videos:**
Screenshot from 2024-12-15 11-11-11
[Screencast from 2024-12-15 11-11-17.webm](https://github.com/user-attachments/assets/e34cab4c-0886-4bb0-b76a-736078c5bac0)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Comment by Pavankumar07s** [comment]
@benjagm could you please  help me guiding in this 1 failed check.

**Comment by aialok** [comment]
> @benjagm @DhairyaMajmudar could you please help me guiding in this 1 failed check.

image

This is actual issue. 
There is some problem while importing the modules.

https://github.com/json-schema-org/website/actions/runs/12336270604/job/34428606371?pr=1162

**Comment by Pavankumar07s** [comment]
@aialok I have noticed this error in the build information. I would like to understand why this error is occurring and learn about the reasons behind it.

**Comment by DhairyaMajmudar** [comment]
@Pavankumar07s the errors are raising since `index` and `ambassador` are implicity typed as any, place proper type defination for both of these.

An another issue is with the import statement of ambassador.json file. Fix them all then you'll be good to go

**Comment by Pavankumar07s** [comment]
@DhairyaMajmudar Alright 👍

**Comment by benjagm** [comment]
@Pavankumar07s Please make sure you run the command `git submodule update` to update the github submodules and make sure the `community` repo added as submodule is properly updated.  Remember that the ambassadors data is maintained in another repo, not here.

The ambassadors.json we are using is a symlink in data/ambassadors.json pointing to the ambassadors.json of the github submodule pointing to community.

About github submodules:
https://git-scm.com/book/en/v2/Git-Tools-Submodules

About symlinks:
https://www.futurelearn.com/info/courses/linux-for-bioinformatics/0/steps/201767#:~:text=A%20symlink%20is%20a%20symbolic,directory%20in%20any%20file%20system.

**Comment by Pavankumar07s** [comment]
Alright @benjagm

**Comment by DhairyaMajmudar** [comment]
@Pavankumar07s the problem with workflow is fixed pls. merge your PR with the main and resolve conflicts

**Comment by Pavankumar07s** [comment]
Alright @DhairyaMajmudar 👍

**Pull request closed without merging**
