### PR TITLE
fix: Incorrect Times/Timezones when fetching events

### PR DESCRIPTION
**Pull request by techmannih**
**What kind of change does this PR introduce?**
Fixing a Bug, Incorrect Times/Timezones when fetching events from the Community calendar #1036 
**Issue Number:**
Issue #1036 

**Screenshots/videos:**
image

### CODE REVIEW

**Comment by techmannih** [comment]
@DhairyaMajmudar @benjagm please review

**Comment by DhairyaMajmudar** [comment]
@techmannih the build and lint workflows are failing, pls. fix them

**Comment by techmannih** [comment]
> @techmannih the build and lint workflows are failing, pls. fix them

sure, please check now

**Review by benjagm — CHANGES_REQUESTED** [review]
Hi @techmannih.

The times are not correct. They should be:
* JSON Schema Open Community Working Meetings should be at 19:00 UTC 
* JSON Schema Office Hours (APAC/Americas) should be at 10:00 UTC
* JSON Schema Office Hours (Europe/Americas) should be at 14:00 UTC

You need to check what is the timezone of the meeting in the calendar and later convert to UTC: 
* JSON Schema Open Community Working Meetings is stored in Europe/London timezone
* JSON Schema Office Hours (APAC/Americas) should be at 10:00 UTC is stored in America/Los_Angeles timezone.
* JSON Schema Office Hours (Europe/Americas) should be at 14:00 UTC is stored in Europe/London timezone.

**Comment by benjagm** [comment]
> Please clarify whether the time on the calendar is in the local time zone or in UTC

* JSON Schema Open Community Working Meetings is stored int the calendar in Europe/London timezone
* JSON Schema Office Hours (APAC/Americas)  is stored in America/Los_Angeles timezone.
* JSON Schema Office Hours (Europe/Americas)  is stored in Europe/London timezone.

We have 2 alternatives:
* Show the times and timezones as they are stored in the calendar.
* Convert all of them to UTC.

Whatever we decide we need the times the be consistent.

**Comment by DarhkVoyd** [comment]
IMO, the schedule would be better displayed in UTC, its easier and clearer to understand for most.

**Comment by gregsdennis** [comment]
Just display both user-local and UTC.

**Comment by benjagm** [comment]
@techmannih, any update on this one? We'd love to fix this asap.

**Comment by benjagm** [comment]
> We can fix the time for Europe/London timezone in UTC, but for the America/Los_Angeles timezone, we need to determine the correct local time based on your needs, as the time difference will vary depending on the season (whether it's Standard Time or Daylight Saving Time).

Great progress!!! Congrats.

We'll use Daylight Saving Time.

**Comment by benjagm** [comment]
> 11:00 PM PDT in Los Angeles would be 6:00 AM UTC (the next day), is it correct ?

Please note that Pacific Daylight Time (PDT) is a North American time zone in use only between the second Sunday in March to the first Sunday in November during Daylight Saving Time (DST). The rest of the year the timezone is PST Pacific Standard Timezone (PC), therefore now they are in PST.

* **NOW** 11pm PST Pacific Standard timezone is 7am UTC
* **During Daylight** 11pm PDT will be 6am UTC

**Comment by benjagm** [comment]
Sidenote about  Office Hours (APAC/Americas) (America/Los_Angeles Time Zone) because here you provided some details that are not correct:

> 3. JSON Schema Office Hours (APAC/Americas) (America/Los_Angeles Time Zone)
> Local Time (America/Los_Angeles Time Zone): 11:00 PM – 12:00 AM

The correct time in the calendar is **3 pm Pacific Time / PT** 

See screenshot:

Screenshot 2024-11-10 at 08 41 15

**Comment by benjagm** [comment]
What you see is a screenshot from Google Calendar in your? In that case there will be some certain of conversation to your local timezone. 

This is what is see (My timezone is CET)

Screenshot 2024-11-10 at 10 18 58

Remember that we are reading the ical file that is a text file from here https://calendar.google.com/calendar/ical/json.schema.community%40gmail.com/public/basic.ics. In this case this is the data available there:

JSON Schema Open Community Working Meeting
````
BEGIN:VEVENT
DTSTART;TZID=Europe/London:20240916T200000
DTEND;TZID=Europe/London:20240916T210000
SUMMARY:JSON Schema Open Community Working Meeting
````

JSON Schema Office Hours (Europe/Americas)
````
BEGIN:VEVENT
DTSTART;TZID=Europe/London:20240604T150000
DTEND;TZID=Europe/London:20240604T160000
SUMMARY:JSON Schema Office Hours (Europe/Americas)
END:VEVENT
````

JSON Schema Office Hours (APAC/Americas)
````
BEGIN:VEVENT
DTSTART;TZID=America/Los_Angeles:20240702T150000
DTEND;TZID=America/Los_Angeles:20240702T160000
SUMMARY:JSON Schema Office Hours (APAC/Americas)
END:VEVENT
````

Don't get confuse about how the data appears in your google calendar. Focus on the ical file, how this is converted to JSON and what JSON you have to work with.

**Comment by benjagm** [comment]
Looks good to me!

**Comment by benjagm** [comment]
Yes!! Can you please add the changes to the logic in the [community](https://json-schema.org/community) page?

We have some duplicity of code and this will be a great opportunity to do some refactoring to avoid duplicate code, if that is possible.

**Comment by benjagm** [comment]
> and it looks much better now.

Looking good. Are you going to do some code reformatting to avoid duplicity in the calendar parsing logic?

**Review by DarhkVoyd — CHANGES_REQUESTED** [review]
Hey @techmannih, what benjagm was trying to convey is that the two files share the same code or function, which leads to redundancy and duplication. To address this issue, we should refactor the code to eliminate duplicate code.

**Review by benjagm — APPROVED** [review]
Great work with this @techmannih Sorry for the delay with the review!! Let's merge it.

**Pull request merged**
