### PR TITLE
Fixing mis-linked pages

### LINKED ISSUE #1038: 🐛 Bug: Mis-linked page (Again)
### Describe the bug

This line of code 
```
const markdownFile = '_indexPage';
```
is faulty, every page with this code which has a "Contribute to this on GitHub" redirects to https://github.com/json-schema-org/website/blob/main/pages/{url}/_index.md , which is a 404.

### Steps To Reproduce

Example:
1. Navigate to https://json-schema.org/overview/faq
2. Click on the Contribute to GitHub button
3. Arrive at https://github.com/json-schema-org/website/blob/main/pages/overview/faq/_index.md (404)
4. Error reproduced

### Expected Behavior

A 200 response on the editable source code page.

### Screenshots

_No response_

### Device Information [optional]

```markdown
- OS: Ubuntu 20.04 Noble
- Browser: Firefox, Chrome
- version: 22
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

### PR DESCRIPTION
**Pull request by IyaadArshad**
**What kind of change does this PR introduce?**
This PR fixes the various 404 issues users encounter when trying to contribute on some pages (Bugfixes)

**Issue Number:**
-  Closes #1038 

**Screenshots/videos:**
image

**Summary**
Fixes the broken contribution buttons

### CODE REVIEW

**Comment by IyaadArshad** [comment]
Full PR not finished yet

**Comment by IyaadArshad** [comment]
I've looked at all the pages which contain this variable with the assigned value before:

```
const markdownFile = '_indexPage';
```

Some of the links correctly return the source code, others return page not found.

Here are the links which use the markdownFile as _indexPage

-----------------------------------------------------------------------------------------------------------------------------------------------------

 https://json-schema.org/learn

Contribution: https://github.com/json-schema-org/website/blob/main/pages/learn/_index.md **(Incorrect)**

Correct page: https://github.com/json-schema-org/website/blob/main/pages/learn/index.page.tsx

------------------------------------------------------

https://json-schema.org/overview/case-studies

Contribution: https://github.com/json-schema-org/website/blob/main/pages/overview/case-studies/_index.md **(Incorrect)**

Correct page: https://github.com/json-schema-org/website/blob/main/pages/overview/case-studies/index.page.tsx

--------------------------------------------------------

https://json-schema.org/specification/migration

Contribution: https://github.com/json-schema-org/website/blob/main/pages/specification/migration/_index.md (Correct)

-------------------------------------------------------

https://json-schema.org/understanding-json-schema

Contribution: https://github.com/json-schema-org/website/blob/main/pages/understanding-json-schema/_index.md (Correct)

------------------------------------------------------

https://json-schema.org/overview/use-cases

Contribution: https://github.com/json-schema-org/website/blob/main/pages/overview/use-cases/_index.md **(Incorrect)**

Correct page: https://github.com/json-schema-org/website/blob/main/pages/overview/use-cases/index.page.tsx

--------------------------------------------------------------------

https://json-schema.org/specification/release-notes

Contribution: https://github.com/json-schema-org/website/blob/main/pages/specification/release-notes/_index.md (Correct)

---------------------------------------------------------------------

https://json-schema.org/specification/json-hyper-schema

Contribution: https://github.com/json-schema-org/website/blob/main/pages/specification/json-hyper-schema/_index.md (Correct)

--------------------------------------------------------------

https://json-schema.org/understanding-json-schema/reference

Contribution: https://github.com/json-schema-org/website/blob/main/pages/understanding-json-schema/reference/_index.md (Correct)

------------------------------------------------------------------

**Comment by Relequestual** [comment]
Looks like you need to run linting and fix the lint errors to pass the PR checks =]
Then it should build and deploy a preview of the site with the PR.

**Comment by benjagm** [comment]
Hi, @IyaadArshad, The referenced issue is already assigned to another contributor, and they are actively working on it. For that reason we are going to close this one in favour of #1187 . Next time please wait to get assigned to an issue before start working on it.

**Pull request closed without merging**
