### PR TITLE
fixed the footer space issue

### PR DESCRIPTION
**Pull request by Ali7040**
**What kind of change does this PR introduce?**
remove the mx-auto form sidebar because we have mx-4 and mx-auto both in same line. and fix the footer space issue.

**Issue Number:**

-  Closes ##455 
-  Related to #___ 
-  Others? 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Review by DhairyaMajmudar — APPROVED** [review]
Here in place of `h-[100vh]` you can use  `h-screen` both will work same but the suggested one is a good practice to use.

Rest looks good to me  : )

**Comment by Ali7040** [comment]
> Here in place of `h-[100vh]` you can use `h-screen` both will work same but the suggested one is a good practice to use.
> 
> Rest looks good to me : )
Thanks for your feedback. I will update it.

**Comment by Ali7040** [comment]
> Here in place of `h-[100vh]` you can use `h-screen` both will work the same but the suggested one is a good practice to use.
> 
> Rest looks good to me : )

Done :)

**Review by benjagm — APPROVED** [review]
Good job!

**Comment by officeneerajsaini** [comment]
Great @Ali7040

**Pull request merged**
