### PR TITLE
Enchantment Dark Mode Toggle shows a popup 

### LINKED ISSUE #726: ✨ Enhancement: Dark/Light mode toggle can be confusing
### Is your feature request related to a problem? Please describe

The dark/light mode button in the upper left of every page operates to say, "click this to go to the mode indicated by the icon."  For example, in dark mode, it shows a sun; and in light mode, it shows a moon.

It shows the mode that that clicking the button would result in.  However, typically, I think of a toggle as showing the mode that you _are_ in.

That said, I can also see that some people might expect the current behavior.

As a result, I'm not sure that the current button adequately caters to all perspectives.  It might seem correct for some, but it's definitely backwards for me.

### Describe the solution you'd like

https://chirpy.cotes.page/ uses a single icon that's just color-flipped with the theme.  The icon indicates both light and dark, indicating that the button toggles between them.

image image

Our current button shows the state, but Chirpy's doesn't.  Chirpy's doesn't carry a state because the theme _is_ the state.  You can plainly see which mode you're in.  The button icon merely needs to indicate that it changes the state.

I'm not saying we need to use _this_ icon, but I think this approach is better.

### Describe alternatives you've considered

The other option is to have a slider toggle, but that takes up more room on the page, and doesn't really fit with the iconography theme we have in the upper right of just single icons.

### Additional context

_No response_

### Are you working on this?

No

### PR DESCRIPTION
**Pull request by JeelRajodiya**
**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #726  

**Screenshots/videos:**

input

### CODE REVIEW

**Comment by JeelRajodiya** [comment]
I discovered some issues with the icons while setting the theme to **system**, please see the below screenshot. 

image

Should I push fix for this issue on this branch?

**Review by benjagm — APPROVED** [review]
Goof stuff Zeel! Thanks!

**Comment by benjagm** [comment]
Hi Zeel. Please see this comment:

https://github.com/json-schema-org/website/issues/726#issuecomment-2166795704

**Comment by JeelRajodiya** [comment]
we are ready to merge

**Review by benjagm — APPROVED** [review]
Looks great!

**Pull request merged**
