### PR TITLE
Rename JSON Toolkit to Blaze

### PR DESCRIPTION
**Pull request by jviotti**
We extracted the JSON Schema validator out of the JSON Toolkit project into a project of its own, called "Blaze", which depends on JSON Toolkit.

Also see https://github.com/bowtie-json-schema/bowtie/pull/1593

### CODE REVIEW

**Review by DarhkVoyd — APPROVED** [review]
@jviotti  Great! Blazing fast! But wouldn't you add `Blaze` as a separate `validator` tool instead of pointing `JSON Toolkit` source to `Blaze`?

**Comment by jviotti** [comment]
True. Let me do that!

**Comment by jviotti** [comment]
Done! Please take another look

**Review by DarhkVoyd — APPROVED** [review]
Looks great to me! Thanks

**Review by benjagm — APPROVED** [review]
Looks great. Thanks Juan!

**Pull request merged**
