### PR TITLE
[Feat]: Add Community Page

### LINKED ISSUE #280: Create a new page for Community inside the Overview Section of the Docs.
#### Description
Create a new page for Community inside the Overview Section of the Docs.
 * Explaining all community channels.
 * All community meetings.
 * Blog.
 * All community programs.
 * Members of the tsc, contributors and ambassadors.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

### PR DESCRIPTION
**Pull request by officeneerajsaini**
I make a new saprate community page

**What kind of change does this PR introduce?**
Feature

**Issue Number:**

-  Closes #280

### CODE REVIEW

**Comment by officeneerajsaini** [comment]
@benjagm done ✅

**Review by benjagm — CHANGES_REQUESTED** [review]
Amazing job here!! CONGRATS!!

Just some comments:
* Can you change the color and font size of the card titles to be our corporative blue instead of purple?
* JSON Schema Community title: Can you make the fonts bigger?
* Events list: We have a lot of space to improve it. Can you build a better display for that section? See an idea here: https://dribbble.com/shots/16742982-Events-List-UI-Design
* Blogs: This card needs some work. At the left side there should be a title, description and button like you did in ambassadors. At the right side we need to put what you actually have at the left side, the last published article.

We are almost there!!

**Comment by officeneerajsaini** [comment]
I'm happy because you like my work. But first, I need to confirm something. As you mentioned before, 'Create a new page for Community inside the Overview Section of the Docs.' However, I added this in the navbar section of the community. I think that's a great place for it. What do you think? Where do we need to add this page?

**Comment by benjagm** [comment]
> I'm happy because you like my work. But first, I need to confirm something. As you mentioned before, 'Create a new page for Community inside the Overview Section of the Docs.' However, I added this in the navbar section of the community. I think that's a great place for it. What do you think? Where do we need to add this page?

I like what you did. Great job. Thanks for thinking out of the box.

**Comment by benjagm** [comment]
Hi @officeneerajsaini . Did you check my last comment? https://github.com/json-schema-org/website/pull/493#pullrequestreview-1930652322

**Comment by benjagm** [comment]
In addition. You did an amazing job with the orbits moving with users avatars, however I think this is a direct copy of what AsyncAPI did. They did it so cool se better to keep the privilege for them. Let's do something different still showing some avatars. I leave here a good example:

https://docs.astro.build/en/getting-started/

**Comment by officeneerajsaini** [comment]
Yes, I copied from AsyncAPI, but now I will create something different.

**Comment by VivekJaiswal18** [comment]
@benjagm if you approve can I also pitch a design for the community page.

**Pull request closed without merging**
