### PR TITLE
Improved the design of TableOfContent custom tag.

### LINKED ISSUE #571: ✨ Enhancement: Improve the design of TableOfContent custom tag.
### Is your feature request related to a problem? Please describe

We have a certain number of custom tags that can be used in markdown to enhance the resulting webpage. Most of them are actually documented here: https://json-schema.org/md-style-guide

One of the tags is TableOfContent. This tag generates a table of contents, however the resulting design needs improvement. See: https://json-schema.org/specification-links

Screenshot 2024-03-21 at 09 51 15

### Describe the solution you'd like

The resolution of this issue implies:

- Add the documentation of how to use the TableOfContent tag into the guide: https://json-schema.org/md-style-guide
- Enhance the resulting html code to make the resulting table of contents look great in light and dark theme.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Are you working on this?

No

### PR DESCRIPTION
**Pull request by vinfinity7**
**What kind of change does this PR introduce?**
This PR has updated the design of the TableOfContent custom tag .

**Issue Number:**

-  Closes #571 - Add any additional notes or references here -->

**Screenshots/videos:**
From 
image

to 

image

**If relevant, did you update the documentation?**
I have not updated the documentation till now .

**Summary**

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Review by benjagm — CHANGES_REQUESTED** [review]
What a improvement! We are almost there.

I think will be better if all the lines have the same colour because now it is different (see image):

Screenshot 2024-04-15 at 08 02 59

I addition I think the circle should be filled with the same color than its border.

With this small improvements we'll be ready to merge.

Excellent work!!

**Comment by vinfinity7** [comment]
Current State after reviewing the changes suggested
image

**Comment by vinfinity7** [comment]
Linting is failing although it works on local ?

**Comment by DhairyaMajmudar** [comment]
> Linting is failing although it works on local ?

You can fix them by the suggestions given by workflow.

**Comment by vinfinity7** [comment]
Yes @DhairyaMajmudar  , turns out the symbols that i've used aren't used by prettier , so i gotta think another wat round for this

**Comment by benjagm** [comment]
@vinfinity7 let me know if you need help with this.

**Comment by gregsdennis** [comment]
The second- and third-level indentions are different. The third level indents more from the second than the second does from the first.

**Comment by benjagm** [comment]
Hi @vinfinity7 are you still working on this? Shall we invite other contributors to give it a try?

**Comment by benjagm** [comment]
Closed for inactivity.

**Pull request closed without merging**
