### PR TITLE
Fix: Dark theme footer style

### LINKED ISSUE #526: 🐛 Bug: After deploying the dark theme we have lost changes done in #375
### Describe the bug

We have lost changes done in https://github.com/json-schema-org/website/issues/375

### Steps To Reproduce

Check the footer.

### Expected Behavior

We need to bring back the footer merged in https://github.com/json-schema-org/website/issues/375

### Screenshots

_No response_

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

### PR DESCRIPTION
**Pull request by Sahil-Shadwal**
**What kind of change does this PR introduce?**
This PR brings back the changes of footer that was previously merged in #375 but in dark mode.

**Issue Number:**

-  Closes #526 

**Screenshots/videos:**
Screenshot from 2024-03-13 20-45-54

**If relevant, did you update the documentation?**
Not relevent

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by benjagm** [comment]
> I am looking into it . Rest of the footers in other pages is fine, i guess something must be overwriting it .

We fixed that in the past too. See this: https://github.com/json-schema-org/website/issues/492

**Comment by DhairyaMajmudar** [comment]
@Sahil-Shadwal can you pls. fix the search box widths, attaching the screenshots for that

Before:
image


After:
image

**Comment by Sahil-Shadwal** [comment]
@DhairyaMajmudar i am sorry man but there is no easy way around it. Even tried the code from before the dark-mode and that's not working either. Will keep looking if i find a solution,then i will let you know.

**Comment by aialok** [comment]
One approach is to create a new branch from the current dark theme branch and revert back to the commit where those changes still exist. Then, merge the dark theme branch with the new branch, which will likely result in a merge conflict. Handle the merge conflict by incorporating the necessary changes.

This problem arises due to inadequate handling of merge conflicts..

**Comment by aialok** [comment]
One approach is to create a new branch from the current dark theme branch and revert back to the commit where those changes still exist. Then, merge the dark theme branch with the new branch, which will likely result in a merge conflict. Handle the merge conflict by incorporating the necessary changes.

This problem arises due to inadequate handling of merge conflicts..

**Comment by DhairyaMajmudar** [comment]
Yup almost all the lost changes are reverted back but the changes with search box are a bit sensitive since it's changed a lot.

**Review by benjagm — APPROVED** [review]
Great job! Thanks!!

**Pull request merged**
