### PR TITLE
Fix: Sponsors Button Not Working Correctly

### LINKED ISSUE #1067: 🐛 Bug: Sponsors Button Not Working Correctly
### Describe the bug

While the "Add your brand here" technically works, most users would perceive this as not working / broken, as only the text saying "Your logo here" has a href referencing the link, meaning the rest of the button, inclusive of the "+" icon does not function, providing a misleading idea that it is a broken link

### Steps To Reproduce

1. Navigate to https://json-schema.org/ (Note: adding #sponsors only works some of the time for some reason, directly going to https://json-schema.org/#sponsors does not open sponsors instantly)
2. Scroll down to "Sponsors"
3. The buttons mentioned in the bug description are visible

### Expected Behavior

Typically, users should expect that the entire button be responsive, perhaps also adding a target=blank or _blank to open in a new tab (not necessary, just personal opinion), but most of the button is unresponsive and does not go to the contribute url

### Screenshots

https://github.com/user-attachments/assets/ba6af677-b2bd-430c-8c07-4c17d79de842

### Device Information [optional]

```markdown
- OS: Ubuntu 22.04
- Browser: edge
- version: 22
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

### PR DESCRIPTION
**Pull request by IyaadArshad**
**What kind of change does this PR introduce?**

- Makes the entire area of the sponsors' section 'Add your logo here' button clickable
- Makes the sponsor page open in a new tab

**Issue Number:**
-  Closes #1067 

**Summary**

- Fixes 'broken' sponsors button

### CODE REVIEW

**Comment by IyaadDev** [comment]
will fix latest issues with eslint soon

**Comment by IyaadDev** [comment]
ready to merge 👍

**Comment by IyaadDev** [comment]
@DhairyaMajmudar any people to provide an approving review?

**Review by DarhkVoyd — COMMENTED** [review]
When clicking on `+ Your Logo Here` for a Tier, wouldn't it make more sense to redirect to that specific Tier contribution checkout instead of the JSON Schema Contribution page. For example, clicking on Golden Sponsor gets [here](https://opencollective.com/json-schema/contribute/golden-sponsor-68354/checkout)

**Comment by IyaadDev** [comment]
It would, I'll update the pr

**Comment by IyaadDev** [comment]
Done

**Review by DarhkVoyd — COMMENTED** [review]
Why is `n8n_logo` removed as part of this PR?

**Comment by IyaadDev** [comment]
it was marked as an unused variable

**Review by DarhkVoyd — CHANGES_REQUESTED** [review]
Hey, thanks. It would be better to keep the changes limited to the issue and fix the unused code separately after being certain about the initial reason for its presence and the reason it’s no longer needed.

**Comment by IyaadArshad** [comment]
👍 - Will provide updated one soon

**Pull request closed without merging**
