### PR TITLE
Update submmodules for meta-schema updates

### PR DESCRIPTION
**Pull request by jdesrosiers**
I believe this is necessary for the meta-schema updates to get deployed to the website.

### CODE REVIEW

**Review by gregsdennis — APPROVED** [review]

**Comment by gregsdennis** [comment]
The submodules are defined by the branch, and the target branch updated, so I suppose it would update automatically.  But then git may just save the commit under the covers. Not sure.  Update away!

**Comment by gregsdennis** [comment]
Looks like it tracks the commit!

https://twitter.com/dahlbyk/status/1721713140352639165?t=YjUPexxsu2RaKbtvYgeFAg&s=19

**Comment by dahlbyk** [comment]
> Looks like it tracks the commit!

Hey, that's me!

There are a few options to auto-update the submodule: https://stackoverflow.com/questions/64407333/using-github-actions-to-automatically-update-the-repos-submodules. TIL Dependabot can [send you PRs for submodule updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem).

**Review by Relequestual — APPROVED** [review]

**Comment by Relequestual** [comment]
Thanks for jumping in @dahlbyk.
Sadly it looks like Dependabot can't target a tag for submodule update [yet](https://github.com/dependabot/dependabot-core/issues/1639).
This happens pretty infrequently to be fair.

**Comment by gregsdennis** [comment]
I suppose this deserves some sort of announcement.  I'll post in Slack.  If we need something more, I can do that, too.

**Pull request merged**
