### PR TITLE
corrected the formatting issue of the json code of the section "$dynamicRef and $dynamicAnchor"

### PR DESCRIPTION
**Pull request by Adity20**
GitHub Issue: https://github.com/json-schema-org/website/issues/371

Summary: This pull request is being made proactively to fix a particular problem. Even though the task didn't have a formal assignment, I felt driven to do it since I was eager to help the project get better.
But there can be further enhances with this section of UI.
Screenshot 2024-02-28 122859

Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)

No
[JUSTIFICATION]
The proposed modifications aim to improve the project without requiring major architectural choices. As a result, I don't think this PR needs an ADR.

### CODE REVIEW

**Comment by Min2who** [comment]
Hi @Adity20, thank you for your pull request! Adding a link to the original issue you're addressing would greatly assist reviewers in understanding the context. Additionally, including a brief description of what this pull request accomplishes would be very helpful. Thanks again for your contribution!

**Comment by Adity20** [comment]
I have added a link to the original issue I am addressing with this PR and added a brief description of what this pull request aims to accomplish. Kindly review it now

**Review by gregsdennis — CHANGES_REQUESTED** [review]
> Even though the task didn't have a formal assignment, I felt driven to do it since I was eager to help the project get better.

In the future, please wait for the task to be assigned.

We already have #379 submitted by another contributor to address this.

**Comment by Adity20** [comment]
The task was assigned to me only by @benjagm . But @jayprakash25 made the pull request just after 1 hour or so. That's why I said that line I wanted to do it so I also made the PR for this issue.
Screenshot 2024-02-28 130050

**Comment by jayprakash25** [comment]
Hi @Adity20 ,
I apologise for the confusion I may have caused. My intention was to contribute to the project eagerly, and I didn't realise the task has already been assigned.

**Comment by gregsdennis** [comment]
@benjagm and I will discuss to resolve these PRs.

**Comment by Adity20** [comment]
> Hi @Adity20 , I apologise for the confusion I may have caused. My intention was to contribute to the project eagerly, and I didn't realise the task has already been assigned.

It's okay you don't need to apologize for anything. The motive is to fix and bug and you did it so It's okay:)

**Comment by jayprakash25** [comment]
> > Hi @Adity20 , I apologise for the confusion I may have caused. My intention was to contribute to the project eagerly, and I didn't realise the task has already been assigned.
> 
> It's okay you don't need to apologize for anything. The motive is to fix and bug and you did it so It's okay:)

I'm glad we share the same goal.

**Comment by Adity20** [comment]
Thanks @benjagm and I am already on it and trying to incorporate all the ideas suggested by @gregsdennis.

**Pull request closed without merging**
