### PR TITLE
Fix: Bad contrast in the blog's dark theme in info boxes 

### LINKED ISSUE #1070: 🐛 Bug: Bad contrast in the blog's dark theme in info boxes
### Describe the bug

The text in info boxes cannot be read.

### Steps To Reproduce

0. Set your browser to prefer the dark theme.
1. Go to https://json-schema.org/blog/posts/applicability-json-schema-fundamentals-part-1#putting-everything-together-avoiding-oneof-pitfalls
2. Look for any of the many info boxes.
3. The text is not legible.

### Expected Behavior

Proper contrast of the font and the background for the dark theme

### Screenshots

The light theme looks ok:

### Device Information [optional]

```markdown
- OS: Manjaro
- Browser: Firefox
- version: 131.0.2
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

### PR DESCRIPTION
**Pull request by ritwik-69**
**What kind of change does this PR introduce?**

It fixes the Bad contrast in the Blog info boxes in Dark  theme

**Issue Number:**

-  Closes #1070 
-  Others? 

**Screenshots/videos:**

image
image

**If relevant, did you update the documentation?**

**Summary**
Fixed the info boxes in dark theme in blogs

**Does this PR introduce a breaking change?**
no

### CODE REVIEW

**Comment by ritwik-69** [comment]
@DhairyaMajmudar The changes are not showing in the deployment i tried fixing it but the issue still persists even though it works on my dev server.

**Comment by ritwik-69** [comment]
@Relequestual can u please review my pr?

**Comment by benjagm** [comment]
If the changes are not showing up, it is surely related to the CSS Tailwind purge. We need to make sure we don't concatenate strings to create class names. https://v2.tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html

You will find more details in this PR:
https://github.com/json-schema-org/website/pull/1021

**Comment by ritwik-69** [comment]
@benjagm idk why its still not working

**Review by benjagm — APPROVED** [review]
Great work with this! I just rebase and added a small change and everything seems to be ready to merge.

**Pull request merged**
