### PR TITLE
Feat: Add a new section `resources` in the Docs 

### PR DESCRIPTION
**Pull request by Min2who**
**GitHub Issue:** #282 

**Summary**:

Added resources section basic setup

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No
[JUSTIFICATION]

### CODE REVIEW

**Comment by Min2who** [comment]
**WORK IN PROGRESS**

**Comment by benjagm** [comment]
Hi @Min2who you are getting involved in so much issues and most of them still open. Is better to make sure we close those first  Let's leave this one for others. In addition, you implementation is not data driven, is static markdown, but one of the requirements was to make it fully data-driven.

**Comment by Min2who** [comment]
ok !

**Comment by benjagm** [comment]
Closed as other contributor is working on this.

**Pull request closed without merging**
