### PR TITLE
Addition of navigation buttons on each page of website

### LINKED ISSUE #1072: ✨ Enhancement: Implement the Prev / Next navigation in all the pages
### Is your feature request related to a problem? Please describe

We implemented a component to enable Prev / Next navigation in our docs, however this component need to be enabled in all the pages.

The component is available here: components/NextPrevButton.tsx

### Describe the solution you'd like

To implement it in all docs pages available in the sidebar, please follow these instructions:

1) Add prev and next metadata to the markdown page following this format:

```
---
title: Creating your first schema
section: docs
prev: 
  label: prev
  url: '#1'
next: 
  label: Miscellaneous examples
  url: '#2'
---
```

2) Add the component to the typescript page:

```
import NextPrevButton from '~/components/NextPrevButton';
```

3) Add the component to the body of the page:

```
<NextPrevButton prevLabel={frontmatter.prev.label} prevURL={frontmatter.prev.url} nextLabel={frontmatter.next.label} nextURL={frontmatter.next.url} />
```

Some markdown files are symlink to the content of GitHub submodules, for example, the Sponsors page. In this case, it will be required to create a PR in the community repo to add the metadata to the original markdown and update _includes/community submodule to the latest version once it is merged.

### Implementations steps:

We will create a new PR for each docs section:
 * Overview https://github.com/json-schema-org/website/pull/1084
 * Getting Started
 * Reference
 * Specification

### PR DESCRIPTION
**Pull request by Utkarsh-123github**
**What kind of change does this PR introduce?**
- Enhancement : Added navigation buttons to each page of the website for better navigation throughout the website

**Issue Number:**

-  Related #1072 

**Screenshots/videos:**
- A sample screenshot showing the navigation buttons
Screenshot 2024-12-23 231650

**Summary**
This PR basically adds navigation buttons to each page of the website for better user experience and ease of navigation throughout the website.

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by Utkarsh-123github** [comment]
Thanks @techmannih for mentioning, but that PR which you tagged just provides navigation buttons for the overview and getting started section of the website, but my PR provides navigation for complete website i.e Overview, Getting started, Reference and Specification sections. I think this PR will be more suitable for this enhancement as it provides complete feature

**Comment by benjagm** [comment]
@Utkarsh-123github Please, dont submit a PR to an issue if you have not been assigned to it.

**Comment by Utkarsh-123github** [comment]
Got it @benjagm .
Actually I submitted this PR in addition to the feature which you instructed in the review video of the PR #1084 that we need navigation buttons for every section and you mentioned in the video that other contributors can contribute to other sections. So this PR was related with that.

Anyways, I'll keep in mind and will make sure that same thing doesn't get repeated.

Thank you.

**Comment by benjagm** [comment]
Hi @Utkarsh-123github . Thanks a lot for your contribution! Next time let's sync before sending the PR. Otherwise we can have different people working on the same issue and that is not idea.

We already merged https://github.com/json-schema-org/website/pull/1084 for the Overview Section. Do you mind reviewing this solution and apply the same approach in your PR? What sections are you implementing here?

**Comment by Utkarsh-123github** [comment]
Yes sure @benjagm  , I'll update my PR by tonight.
I am working on navigation of Getting started , Reference and Specifications section.

**Comment by Utkarsh-123github** [comment]
I am closing this PR, will push the changes with a new PR and will update soon.

**Pull request closed without merging**
