### PR TITLE
Feat: Refining issue templates for adding issues in the project board

### LINKED ISSUE #434: ✨ Enhancement: Refine the issue templates
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Id like to refine the setup of the existing issue templates:
* Docs: Assign issues to Docs Team and add new issues to the Project [JSON Schema Docs](https://github.com/orgs/json-schema-org/projects/16)
* Bugs and Enhancements: Assign issue to Triage Team and add new issues to the Project https://github.com/orgs/json-schema-org/projects/11

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Are you working on this?

No

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
**What kind of change does this PR introduce?**

Adding github actions for adding issue labeled `bug`  and ` enactment in the website project board and  `doc` in the documentations project board.

 

**Issue Number:**
-  Closes #434  
-  Related to #434 
-  Others? 

**Screenshots/videos:**
N/A

**If relevant, did you update the documentation?**
Not required for this pr but if needed I will.

**Summary**

Added the GH actions for moving issues in correct project board

**Does this PR introduce a breaking change?**
N/A

### CODE REVIEW

**Comment by benjagm** [comment]
Can we do this using the project field in the template and avoiding a new workflow?

**Review by benjagm — COMMENTED** [review]
See my comment Dhairya:

https://github.com/json-schema-org/website/pull/436#issuecomment-1976479288

**Comment by DhairyaMajmudar** [comment]
Thanks for the suggestion will look into this : )

**Comment by DhairyaMajmudar** [comment]
@benjagm Actually we can do this by adding the `projects` field in the issue template but later on the issue creator has to manually add the project but by using the GH actions it can be done automatically on the basics of issue label 

Would like to get your views on this.

**Comment by benjagm** [comment]
> Actually we can do this by adding the `projects` field in the issue template but later on the issue creator has to manually add the project

What is the meaning of the projects field then? It seems that that field is specifically to automatically add the new issue to that project/board. See [discussion](https://github.com/orgs/community/discussions/9687).

**Comment by DhairyaMajmudar** [comment]
Amazing 😃, from discussion it seems like projects field can now also add the issue to specificed project

**Review by benjagm — APPROVED** [review]
Looks good to me. Thanks!!

**Pull request merged**
