### PR TITLE
Bug: Sponsor logos are not optimized for dark mode

### LINKED ISSUE #524: 🐛 Bug: Sponsor logos are not optimized for dark mode
### Describe the bug

Sponsor logos are (mostly) optimized for a light background [and likely have brand use guidelines prohibiting their use against low-contrast backgrounds].

They therefore (mainly) appear indistinct in dark mode.

### Steps To Reproduce

Navigate to homepage.
Scroll to sponsors.

### Expected Behavior

The background against which sponsor logos are overlaid is suitable for the readability of the logos and conforms to their brand usage guidelines.

### Screenshots

image

### Device Information [optional]

```markdown
- OS: Windows 11
- Browser:Edge / Chrome
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

### PR DESCRIPTION
**Pull request by satyam-x10**
**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #524  
-  Related to #___ 
-  Others? 

**Screenshots/videos:**
Screenshot (32)

**If relevant, did you update the documentation?**

**Summary**
The dark bg was conflicting with the sponsors logo. Since in our color pallete a blue shade is availaible.  i introduced gradient using the same.

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Comment by benjagm** [comment]
We'll need to fix the gradient to be applied in the full width of that section or just for every single logo.

Screenshot 2024-03-13 at 17 31 08

We'll need to do something with the supported by logos too:
Screenshot 2024-03-13 at 17 31 08

**Review by benjagm — CHANGES_REQUESTED** [review]
Thanks for this PR. I left some comments [here](https://github.com/json-schema-org/website/pull/532#issuecomment-1994905483)

**Comment by satyam-x10** [comment]
> Thanks for this PR. I left some comments [here](https://github.com/json-schema-org/website/pull/532#issuecomment-1994905483)

Thanks.. will fix them asap

**Comment by satyam-x10** [comment]
@benjagm have implemented the suggested changes. Thanks

**Comment by benjagm** [comment]
Found 2 things.

The final result is not great. Can we try applying the gradient for each logo instead the whole section?
Screenshot 2024-03-13 at 18 01 29

In addition the gradients
Screenshot 2024-03-13 at 18 01 36
 should be applied only for dark mode and not in light mode:

**Comment by satyam-x10** [comment]
> Left some more comments:
> 
> https://github.com/json-schema-org/website/pull/532#issuecomment-1995010930

Sure I will attend them

**Comment by DhairyaMajmudar** [comment]
Satyam, how's about Instead of applying a gradient, we can use two different variants of the logos each for dark and light. Whenever the website transits in the dark mode the logo gets changed into its light version and vice versa in light mode.

**Comment by satyam-x10** [comment]
> Satyam, how's about Instead of applying a gradient, we can use two different variants of the logos each for dark and light. Whenever the website transits in the dark mode the logo gets changed into its light version and vice versa in light mode.

Wouldn't that change their logo.. I mean they have fixed color and all. Won't it be a problem..?

**Comment by DhairyaMajmudar** [comment]
> > Satyam, how's about Instead of applying a gradient, we can use two different variants of the logos each for dark and light. Whenever the website transits in the dark mode the logo gets changed into its light version and vice versa in light mode.
> 
> Wouldn't that change their logo.. I mean they have fixed color and all. Won't it be a problem..?

I think every logo has its both black and white versions. eg: Apprite logo

**Comment by satyam-x10** [comment]
How is this looking?

**Comment by benjagm** [comment]
Not so good. Let me find the opposite version of each logo so we can switch them

**Comment by benjagm** [comment]
Let me find the inverted version of the logos so we can switch them.

**Comment by satyam-x10** [comment]
> Let me find the inverted version of the logos so we can switch them.

Sure . Thanks.. if not then we can apply css filter

**Comment by benjagm** [comment]
> > Let me find the inverted version of the logos so we can switch them.
> 
> Sure . Thanks.. if not then we can apply css filter

I was looking for the white version of the logos but some doesn't have them so I did some additional research and maybe we can find a way to make it work doing a better usage of the logos to inherit colors from the css. Please see the last response to this discussion:
https://stackoverflow.com/questions/71013868/switch-logo-color-in-dark-mode-issue

Lets try one the second solution using svg+use and CSS.

````
<svg>
    <use href="logo.svg#logo-symbol">
  </svg>  
````

**Comment by DhairyaMajmudar** [comment]
Satyam, the sponsors logo we are using are in `.svg` file which means we can programmatically modify them according to our need : )

I am sharing a .zip folder from which you can get all the required white version logos

[Sponsore_logo_white.zip](https://github.com/json-schema-org/website/files/14603649/Sponsore_logo_white.zip)

**Comment by satyam-x10** [comment]
> Satyam, the sponsors logo we are using are in `.svg` file which means we can programmatically modify them according to our need : )
> 
> I am sharing a .zip folder from which you can get all the required white version logos
> 
> [Sponsore_logo_white.zip](https://github.com/json-schema-org/website/files/14603649/Sponsore_logo_white.zip)
> 
> 

Thank you very much..

**Comment by gregsdennis** [comment]
(legal) We need to verify with each sponsor's branding guidelines to see what they have that's compatible with a dark mode.

Many companies will already have logo presets for this. We definitely SHOULD NOT be modifying their logos.

**Comment by benjagm** [comment]
> (legal) We need to verify with each sponsor's branding guidelines to see what they have that's compatible with a dark mode.
> 
> Many companies will already have logo presets for this. We definitely SHOULD NOT be modifying their logos.

Fair point. I'll reach out to each sponsor to ask for their updated logos. Thanks!!

**Comment by satyam-x10** [comment]
> > (legal) We need to verify with each sponsor's branding guidelines to see what they have that's compatible with a dark mode.
> > 
> > Many companies will already have logo presets for this. We definitely SHOULD NOT be modifying their logos.
> 
> Fair point. I'll reach out to each sponsor to ask for their updated logos. Thanks!!

That would be best . Thanks

**Comment by satyam-x10** [comment]
> > (legal) We need to verify with each sponsor's branding guidelines to see what they have that's compatible with a dark mode.
> > Many companies will already have logo presets for this. We definitely SHOULD NOT be modifying their logos.
> 
> Fair point. I'll reach out to each sponsor to ask for their updated logos. Thanks!!

i have temporarily updated it with the files provided by @DhairyaMajmudar . Will update it once we have the final logo.

**Comment by benjagm** [comment]
Hi everyone. Some updates for the logos list: Please remove Stoplight and Retool from the list of sponsors.


Please find here the official logos:

- AsyncAPI Logos: https://github.com/asyncapi/brand
- Airbnb Logos: https://brandfolder.com/airbnb
- Postman: Already in the hero section
- Apideck: https://res.cloudinary.com/apideck/image/upload/w_auto,f_auto/v1613094631/marketplaces/w8jsdbnq5dvwxait0qor.png
- Endjin: same logo
- LLG.org: Attached
llc-logo_white
- Common room: 
- Slack: Please update the black and white logos from here: https://slack.com/intl/en-gb/media-kit

The only pending logo is Common Room but I hope to receive it asap.

**Comment by satyam-x10** [comment]
> Hi everyone. Some updates for the logos list: Please remove Stoplight and Retool from the list of sponsors.
> 
> Please find here the official logos:
> 
> * AsyncAPI Logos: https://github.com/asyncapi/brand
> * Airbnb Logos: https://brandfolder.com/airbnb
> * Postman: Already in the hero section
> * Apideck: https://res.cloudinary.com/apideck/image/upload/w_auto,f_auto/v1613094631/marketplaces/w8jsdbnq5dvwxait0qor.png
> * Endjin: same logo
> * LLG.org: Attached
>   llc-logo_white
> * Common room:
> * Slack: Please update the black and white logos from here: https://slack.com/intl/en-gb/media-kit
> 
> Lets make sure you use the svg version of the logos.
> 
> The only pending logo is Common Room but I hope to receive it asap.

Thank you very much @benjagm . i have made proper changes and pushed the final code.. i have stored the logos for dark theme in a new folder an used them.

**Review by benjagm — APPROVED** [review]
Thanks. Looks fantastic. Will merge this into to development branch.

**Comment by DhairyaMajmudar** [comment]
Hi Satyam, can you pls. once verify if you are also facing this problem on Postman logo not visible in the light theme.

image

**Comment by satyam-x10** [comment]
> Hi Satyam, can you pls. once verify if you are also facing this problem on Postman logo not visible in the light theme.
> 
> image
> 

It working fine for me can you inspect and check the url of the rendered images..

**Pull request merged**
