### PR TITLE
chore(github-actions): update contributor and project sync workflows

### PR DESCRIPTION
**Pull request by aialok**
**What kind of change does this PR introduce?**

- Since we have branch protection rules, automated commits can't be made. Therefore, both workflows will now create pull requests instead.

**Issue Number:**
- None

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Review by benjagm — CHANGES_REQUESTED** [review]
Great job with this!

Could it be possible to add another step to approve and another one to merge?

**Comment by aialok** [comment]
> Great job with this!
> 
> Could it be possible to add another step to approve and another one to merge?

I don't think it's possible to do this within the same workflow since we need to create the pull request first which take time, then approve it, and finally merge it. But lemme check.

However, it could be easily done with a separate workflow.

**Comment by benjagm** [comment]
> However, it could be easily done with a separate workflow.

We'll need to do something to avoid the cumulation of unreviewed PRs.

**Comment by aialok** [comment]
> > However, it could be easily done with a separate workflow.
> 
> We'll need to do something to avoid the cumulation of unreviewed PRs.

I will be creating another workflow to approved and merged the pr.

**Comment by aialok** [comment]
Added auto approve and auto merge in the same workflow.

**Comment by aialok** [comment]
For auto merge condition must  be true:
image


https://github.com/peter-evans/enable-pull-request-automerge?tab=readme-ov-file#conditions

**Comment by gregsdennis** [comment]
> Added auto approve and auto merge in the same workflow.

This seems like a bad idea.  (Unless I'm misunderstanding what's being added.)

It seems like you're wanting an action to automatically approve and merge PRs?  Why?  PRs are intended for _review_... by humans.

**Comment by aialok** [comment]
> > Added auto approve and auto merge in the same workflow.
> 
> This seems like a bad idea.  (Unless I'm misunderstanding what's being added.)
> 
> It seems like you're wanting an action to automatically approve and merge PRs?  Why?  PRs are intended for _review_... by humans.

Basically, both workflows work to fetch the latest contributor data and our roadmap project data and save it in a file. This allows us to use the data on our website, helping to reduce the number of API calls to GitHub by using the data directly from a JSON file.

And since we have branch protection rule we can't directly push to main branch. We need to create pull request first.

https://github.com/json-schema-org/website/pull/869#pullrequestreview-2244053294

**Comment by gregsdennis** [comment]
> And since we have branch protection rule we can't directly push to main branch. We need to create pull request first.

Then maybe this repo isn't the best place to store the results of the data fetch.  Maybe we store it in another repo (or a gist) where only the bot has push rights (and maybe the project admins).  I use a [gist](https://gist.github.com/gregsdennis/28607f2d276032f4d9a7f2c807e44df7) to store some data for a custom badge on my repo ([action](https://github.com/json-everything/json-everything/blob/119788d83e3b016ba1fe8a0c5deb019b0193fad2/.github/workflows/dotnet-core.yml#L91-L100)).

Automation like this seems subversive to me.  When I encounter hacks like this, it usually means I've taken a wrong turn somewhere; that I'm doing something wrong.

**Comment by benjagm** [comment]
> Automation like this seems subversive to me. When I encounter hacks like this, it usually means I've taken a wrong turn somewhere; that I'm doing something wrong.

Hi everyone here. This is the solution I suggested and I take responsibility. The fetched files will be used to build a future roadmap page and improve the current community page. We are storing the data to avoid doing synchronous API calls and avoid rate limit issues. I understand your concerns and I am happy to discuss alternatives. Gist seems like over-complicating things but I have never implemented it before. I know that AsyncAPI is doing something similar to us in their repository.

**Comment by gregsdennis** [comment]
I expect you're looking at something like https://github.com/asyncapi/website/pull/3142?

If that's the direction you want to go, okay.  I've given my opinion.

**Review by benjagm — APPROVED** [review]
LGTM

**Pull request merged**
