### PR TITLE
Add sitemap using next-sitemap

### PR DESCRIPTION
**Pull request by benjagm**
Related: #152

### CODE REVIEW

**Comment by Relequestual** [comment]
Doesn't seem to show for the PR preview.
I tried two fixes based on https://community.cloudflare.com/t/sitemap-not-available-through-cloudflare-pages/384330/4
Neither have made the sitemap appear.

**Comment by benjagm** [comment]
What fixed this was providing the build parameters in cloudflare because it is not using the next config of the repo.

**Comment by Relequestual** [comment]
That's annoying. Can you add a new issue for someone to find out if you can make cloudflare use the config in the repo, and document in the readme whatever they find out please? =]

**Comment by benjagm** [comment]
Hi Ben. What I meant was the Build setting. You can have build setting in your package.json but Cloudflare has its own build setting that you should configure, so what made this work in our case was the right code in next.config.js and next-sitemap.config.js and the right build commands on cloudflare. See image below:

Screenshot 2023-10-16 at 09 51 30

**Comment by Relequestual** [comment]
Understood.
I think the build command should be in the package.json file though, then have the build command in Cloudflare call that.

We can then test making production builds locally, and have better control (in the repo) over the build command.

**Comment by benjagm** [comment]
I have the same command in the package.json working locally too.

**Pull request merged**
