### PR TITLE
Fix: navbar should close when user click anywhere on screen

### LINKED ISSUE #536: ✨ Enhancement: Top Navbar should close when user clicks anywhere on the screen
### Is your feature request related to a problem? Please describe

User should be able to close the top navbar by not only clicking on the cross button but also by tapping anywhere outside the top navbar.
This will make it more ergonomic for the mobile users.

https://github.com/json-schema-org/website/assets/96608169/9126bd13-be5f-43ff-80aa-42d3c5c3f035

### Describe the solution you'd like

This can be solved in various ways like using hooks, etc

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by lalitkumawat1m**
**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #536

**Screenshots/videos:**

https://github.com/json-schema-org/website/assets/91591901/27750533-fefd-4525-b074-1a0172ea470a

**If relevant, did you update the documentation?**
No

**Summary**

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Review by DarhkVoyd — CHANGES_REQUESTED** [review]
Hey, I am unsure about using `document.addEventListener` and directly interacting with the DOM, I suggest we probably use some react event handler such as `onBlur` instead. 

> Normally you shouldn’t need to do this with React: you need to manually locate the elements using refs, which kinda breaks how React should work.

**Comment by lalitkumawat1m** [comment]
Hey @DarhkVoyd, I appreciate your suggestion but Could you please guide me how this can be done without manipulating dom and using onblur?

**Comment by DarhkVoyd** [comment]
Hey @lalitkumawat1m So, after thinking more about it, I think that your approach is the better way. I was earlier thinking about making the navbar focusable and then using onBlur listener to handle blur cases but I realised it would instead be unnecessary. I understand now that the use of `document.addEventListener` is valid in this case.

**Comment by DarhkVoyd** [comment]
The one thing I am still confused about is the use of `showMobileNav` in `useEffect` dependencies array. Would the `ref` be a more valid dependency instead of the open variable.

**Comment by benjagm** [comment]
Hi Lalit. Can you please check the comments done by DV?

**Comment by lalitkumawat1m** [comment]
Hey @benjagm I have made the requested changes. Please have a look

**Comment by DarhkVoyd** [comment]
Looks mostly good. just some suggestions,
1. The issue proposed to close navbar when user clicks anywhere outside the navbar. Now, the implementation and PR are focused on closing the navbar if user clicks anywhere, even on the navbar. But, still the function is named `handleClickOutside`, maintaining consistency would help keep things clear. Also, is this intentional?
2. A general practice suggestion, commit messages descriptive of changes introduced in code are better. This enhances the readability of the project's history. For example, instead of `Made requested changes`, a commit message like `Update useEffect dependency from showMobileNav to mobileNavRef` provides a clearer note of the change.

**Comment by lalitkumawat1m** [comment]
1. Should I rename the handleClickOutside function to handleCloseNavbar ?

2. I will update my commit msg to meaningfully commit msg.

**Comment by DarhkVoyd** [comment]
Sure

**Comment by lalitkumawat1m** [comment]
I have made the changes.

**Review by DarhkVoyd — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
