### PR TITLE
Add workflow to update landscape tooling

### PR DESCRIPTION
**Pull request by DarhkVoyd**
**What kind of change does this PR introduce?**
This PR aims to add a workflow, to track changes to the tooling data file and update tools in our landscape tooling category when tooling data changes.

NOTE: We need to add a fine-grained personal access token named `PERSONAL_ACCESS_TOKEN`, with `write` access to `Actions` of `landscape` repository to have appropriate authentication.

**Issue Number:**

-  Closes #___ 
-  Related to #___ 
-  Others? 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Comment by aialok** [comment]
Why not to use our json-schema-bot token instead of PAT?

**Comment by benjagm** [comment]
You are totally right! My bad! Can you update it DV?

**Comment by DarhkVoyd** [comment]
Hey, sure! I didn't have access to existing token names so I just assumed a new token. Can you provide the name of the existing token? Moreover, please ensure that the token has `read and write` actions permissions.

**Comment by aialok** [comment]
Below is only step need to add to create token and using id you can use that token in other step.





You can also checkout linkchecker workflow, where are using that bot to create  issue.

We might not have permission to trigger workflow but we can update permissiom for it easily.

**Comment by DarhkVoyd** [comment]
Got it, Thanks! I think there was some miscommunication from my side, its not a personal token per say, it was just any token with actions permission I just named it "Personal Access Token"

**Comment by aialok** [comment]
> Got it, Thanks! I think there was some miscommunication from my side, its not a personal token per say, it was just any token with actions permission I just named it "Personal Access Token"
> 

Good part about github app token is that it get destroy after the action finish : )

**Pull request merged**
