### PR TITLE
Parveen/fixed date at draft 4

### PR DESCRIPTION
**Pull request by praveen-rikhari**
**GitHub Issue:** #123 

**Summary**:
- fixed date at draft 4 on file `pages/specification-links.md`

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes/No
No

### CODE REVIEW

**Comment by praveen-rikhari** [comment]
@benjagm Please review.If any other modifications required please let me know.

**Review by benjagm — DISMISSED** [review]
Great job! Approved from my side!

**Comment by praveen-rikhari** [comment]
@benjagm thanks for approving. I thought the fixed version should be on a separate PR.

**Comment by benjagm** [comment]
Let's continue all the changes in #386

**Comment by praveen-rikhari** [comment]
tracking this in #386

**Pull request closed without merging**
