### PR TITLE
Rename implementations section to tools

### PR DESCRIPTION
**Pull request by benjagm**
**GitHub Issue:** #320 
Resolves: #320

**Summary**: This PR renames the Implementations section in favour of Tools

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

### CODE REVIEW

**Comment by Relequestual** [comment]
Thanks!
How do we plan to handle redirects?

**Comment by benjagm** [comment]
> Thanks! How do we plan to handle redirects?

The url is the same. I just renamed the title/buttons.

**Comment by Relequestual** [comment]
We should also do https://json-schema.org/obsolete-implementations
Happy if you want that to be a separate PR, but I think it could be in this one.

**Comment by benjagm** [comment]
> We should also do https://json-schema.org/obsolete-implementations
> Happy if you want that to be a separate PR, but I think it could be in this one.

I just pushed the change to rename that page as well.

**Comment by Relequestual** [comment]
OK. I'm fine with this if we also create a new good first issue to clean up the rest of the site to use "tools" rather than "implementations" everywhere but the spec documents (because we don't change those. I think that would accurately reflect what we want to see.

And in the code, to make it less confusing.

**Comment by gregsdennis** [comment]
> everywhere but the spec documents (because we don't change those.

Also consider that the spec _does_ need to define its term for "implementation".  I still think that it needs to be "software that performs the tasks defined in the spec", which are just validation and annotation.

**Comment by praveen-rikhari** [comment]
Hello @benjagm I was going through the preview for this branch but I still see that we have implementations term being used in the body of the Tools at a lot of places, I was wandering, should that be done in a different PR??

**Comment by praveen-rikhari** [comment]
Screenshot from 2024-02-22 12-17-38
Screenshot from 2024-02-22 12-17-48
Screenshot from 2024-02-22 12-18-00
 
Here are some of them

**Comment by Relequestual** [comment]
@praveen-rikhari Please reference this issue when you do. Thanks.

**Pull request merged**
