### PR TITLE
Bug-UI: Make table responsive

### LINKED ISSUE #502: 🐛 Bug: UI Bug - In the Tools page, table and tags are hidden on Smaller Viewports
### Describe the bug

In the Tools page, on medium and small-sized viewports (<600), the tags and table in the validator section are not visible properly. The name of validator tags seems to be cut-off by small amout for medium devices, and more for smaller devices.

### Steps To Reproduce

- Go to https://json-schema.org/implementations , and try decreasing the viewport width below ~600. The cutoffs will start to become visible

### Expected Behavior

The table and its associated tags should remain completely visible and correctly formatted on medium and small-sized viewports. They should adapt to the available screen space.

### Screenshots

json-schema org_implementations (1)
json-schema org_implementations

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

### PR DESCRIPTION
**Pull request by ayushtiwari110**
**What kind of change does this PR introduce?**
- Refactoring: This PR aims to make the implementations table responsive on different screen sizes.

**Issue Number:**

-  Closes #502  

**Screenshots/videos:**
- After refactoring
small
medium
large

**Summary**
- Reduced text sizes on smaller screens to optimize table layout.
- Implemented horizontal scrolling on the table to enhance responsiveness and ensure complete content visibility.

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Review by benjagm — CHANGES_REQUESTED** [review]
This is looking much much better!! We are almost there.

I'd like to suggest to hidden all columns at the right hand side that goes after the Drafts column so we avoid cutting content (see image)
Screenshot 2024-03-12 at 10 19 17

**Comment by ayushtiwari110** [comment]
Thanks for the review, it was a good suggestion. I have implemented the changes requested.
I guess now it's perfectly scaling for small screens after hiding the last column which was being cut-off:
Screenshot 2024-03-12 172620
Please review the above changes...

**Review by benjagm — APPROVED** [review]
Great job! Thanks!!

**Comment by ayushtiwari110** [comment]
Thanks! 🚀

**Pull request merged**
