### PR TITLE
Adding Openapi Links

### LINKED ISSUE #127: add links to openapi website
e.g. from the implementations page to theirs, but there are other pages we should link to too.

```
ether  12:58
all the goodies are listed at https://json-schema.org/implementations.html
12:59
(there are probably others as well, listed on the openapi website, that are openapi-specific.)

ether  12:59
@relequestual we should maybe link to their page from ours

relequestual  27 minutes ago
log an issue =]

ether  < 1 minute ago
you need a slack bot for opening GH issues from the command line
```

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
**GitHub Issue:** #127 
closes #127 

**Summary**:

Added OpenAPI links to the website, changed the `openAPI` text to openAPI links which redirects to the open API website. The links are added to 6 relevant places. 

**Files Changed**
1. `pages/implementations/main.md`

**Screenshot Before**
image

**Screenshot After**
image

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No
[JUSTIFICATION]

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
@benjagm @karenetheridge  pls. have a look, I have added the links to about 6 places where it felt relevant to me. If you needed links to be added in more places I will be happy to do so : )

**Comment by DhairyaMajmudar** [comment]
Thank you @benjagm, I have made the suggested changes.

**Review by benjagm — APPROVED** [review]

**Review by karenetheridge — APPROVED** [review]

**Comment by karenetheridge** [comment]
Before merging, could this be rebased+squashed please?

**Comment by DhairyaMajmudar** [comment]
> Before merging, could this be rebased+squashed please?

Yeah sure

**Pull request merged**
