### PR TITLE
resolved code formatting and indentation issues

### LINKED ISSUE #456: 🐛 Bug: Indentation problems with JsonEditor component
### Describe the bug

We had  issues in the past with the JsonEditor component in small devices because it produced horizontal overflow. For this reason we needed to disable the wrapLines and wrapLongLines attributes  in this commit [cd30786](https://github.com/json-schema-org/website/commit/cd3078604f28ecc1e9c3ad292e399b06cc97c17c) but this is producing unexpected indentation issues like the one discussed [here](https://github.com/json-schema-org/website/pull/385).

The component is this one:
https://github.com/json-schema-org/website/blob/main/components/JsonEditor.tsx

The solution we expect is enable wrapLines and wrapLongLines and add a horizontal scroll bar in component so we producer the best developer experience in all code snippets.

Screenshot 2024-03-05 at 18 32 09

Screenshot 2024-03-05 at 18 32 52

### Steps To Reproduce

Any page with code snippets in mobile devices.

### Expected Behavior

Horizontal scroll bar at the bottom of the component.

### Screenshots

_No response_

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

No

### PR DESCRIPTION
**Pull request by Adity20**
**What kind of change does this PR introduce?**
resolves code indentation issues

**Issue Number:**

-  Closes #456  

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**
A horizontal scrollbar will appear if the code lines will try to exceed the maximum width of container and this will help in solving indentation issues in small devices.

### CODE REVIEW

**Comment by benjagm** [comment]
Please see this page: https://json-schema.org/learn/getting-started-step-by-step and the equivalent in your local environment.

It seems that we are using 2 different components, one called JsonEditor.tsx for json and json-schema and other inside StyledMarkdown.tsx with different behaviour and different styling for the rest of languages. Having 2 components is ok but we need to make them behave similary.

* JSON Editor: Horizontal scroll does not appear, if does a line wrap that is almost ok but still is hidden some text. See line 3.
Screenshot 2024-03-08 at 18 03 03

* Other languages editor: It does not wrap lines, the line numbers have different color than JSON Editor and dues not have the label to copy paste code. This is the one we need to fix. To align with te behavior of JSON Editor we need to make the same line wrap. 
Screenshot 2024-03-08 at 18 04 29

**Review by benjagm — CHANGES_REQUESTED** [review]
Thanks for taking this complex issue. Please see my comment [here](https://github.com/json-schema-org/website/pull/482#issuecomment-1986080126).

Please take a look and let me know.

**Comment by Adity20** [comment]
Yeah I'm working on that part I just wanted to show you the changes of styledMarkdown file if they look good to you or not

**Comment by benjagm** [comment]
> Yeah I'm working on that part I just wanted to show you the changes of styledMarkdown file if they look good to you or not

For styledMarkdown I can't see the scroll bar, nor the line wrap applied in that case (Languages other than json or json schema)

**Comment by benjagm** [comment]
> Yeah I'm working on that part I just wanted to show you the changes of styledMarkdown file if they look good to you or not

For styledMarkdown I can't see the scroll bar, nor the line wrap applied in that case (Languages other than json or json schema)
Screenshot 2024-03-08 at 18 04 29

**Comment by Adity20** [comment]
The changes are visible in 2020-12 release notes section for now 
And I'm trying to find a global solution for all the components.
Sorry for taking so much time but I'll try to complete it as soon as possible

**Comment by benjagm** [comment]
> The changes are visible in 2020-12 release notes section for now And I'm trying to find a global solution for all the components. Sorry for taking so much time but I'll try to complete it as soon as possible

Now I see. It works!!
I couldn't see the scroll bar. Can you please modify the styles of the scroll bar to make it evident? a lighter color, maybe increase the height.

**Comment by Adity20** [comment]
Sure @benjagm I was thinking the same too

**Comment by Adity20** [comment]
Now the scrollbar will be more evident @benjagm I made the changes and now working on the overflow issue and other pages wraplines issue and adding a scrollbar whenever required

**Comment by Adity20** [comment]
@benjagm I have addressed the issue of overflow in https://json-schema.org/draft/2020-12/release-notes.
Kindly review.

**Comment by Adity20** [comment]
@benjagm I am done with the indentation problem of docs page also.
The changes were needed to be done in jsonEditor file for this.
Here's the video of docs section state after the changes I made


https://github.com/json-schema-org/website/assets/119804372/8aa9c086-b958-4e73-9f83-5d3c1098438e

**Comment by Adity20** [comment]
@benjagm kindly review the requested changes.

**Comment by benjagm** [comment]
> @benjagm kindly review the requested changes.

Thanks @Adity20 . The generic code component with scroll works well Congrats!!. Now we need to work on the jsoneditor component to make the same scroll effect for JSON and JSON Schema code snippets.

**Review by benjagm — CHANGES_REQUESTED** [review]
Please see my review comment [here](https://github.com/json-schema-org/website/pull/482#issuecomment-1988568023).

**Comment by benjagm** [comment]
> I already did that @benjagm
> 

That recording shows just the generic component with .NET code snippets. We both agree that component is fixed. 

I am referring to the other component, the one showing  JSON and JSON Schema code snippets: JsonEditor.tsx
That one should have the same behaviour that the one you just fixed.

**Comment by Adity20** [comment]
sorry @benjagm can you please elaborate a little which code snippets you are talking about.

**Comment by benjagm** [comment]
Please see [this comment](https://github.com/json-schema-org/website/pull/482#issuecomment-1986080126). 

I have been speaking about this topic for the last 3 iteration reviews of this PR. If you see this page: https://json-schema.org/learn/getting-started-step-by-step you will realize that the code snippets that shows JSON or JSON Schema have a different look and feel, included a label on top and a button to copy/paste code. 

The source code of that component is different than the one you just fixed. I'd like the JsonEditor component to show an horizontal scroll bar like the one you just added in the standard code editor in StyledMarkdown.tsx

**Comment by Adity20** [comment]
Yeah you are right @benjagm Actually I made the appropriate changes in my local environment codebase and overlooked the actual codebase that is existing.

I'll make the appropriate changes now.
Thanks for the help @benjagm.

**Comment by Adity20** [comment]
Hello @benjagm I have tried some more changes and now the lines are getting wrapped properly without any overflow and the colour formatting is also like the other component. So if you can check whether this looks good to you or not i can proceed with removing the older ones 

https://github.com/json-schema-org/website/assets/119804372/d56eec82-ef46-4611-9b3b-376268c77061

**Review by benjagm — CHANGES_REQUESTED** [review]
You are doing an amazing job!! We are really close to fix this. I found some things that still requires some changes but instead of writing I decided to record a video to make things easier. 

Please check the video (with audio)

https://github.com/json-schema-org/website/assets/40007659/b8116b2e-5db1-4a24-8dd4-8bf82038febe

**Comment by Adity20** [comment]
Hello @benjagm as per your recommendations I tried some changes
Now there is not a difference in colour formatting between generic code component and json or json schema code after the changes i made
And the label is static at it's postion even after the scrollbar gets to the end 

Now tell me one thing do you want to keep the colour formatting difference between the generic component and other component or not.

https://github.com/json-schema-org/website/assets/119804372/df963067-0bf3-40d8-92c6-4271e788b9cb

**Review by DhairyaMajmudar — COMMENTED** [review]
Hi Aditya, here instead of using inline styles using Tailwind utility classes is much preferable since the whole codebase is using them : )

[Tailwind Docs](https://tailwindcss.com/docs/installation)

**Comment by Adity20** [comment]
I already tried @DhairyaMajmudar But here we are having a conflict between two files so once we solve that issue it will be okay
The editable component is not adapting the changes for line break styles. And i tried tailwind classes also.
But if you have any particular suggestion regarding changes in a particular code component let me know

**Comment by DhairyaMajmudar** [comment]
> I already tried @DhairyaMajmudar But here we are having a conflict between two files so once we solve that issue it will be okay The editable component is not adapting the changes for line break styles. And i tried tailwind classes also. But if you have any particular suggestion regarding changes in a particular code component let me know

Sure thing, thanks for clarifying

**Comment by benjagm** [comment]
Hi everyone! The final strategy for code editors has been moved to this issue #560 

We are going to close this PR and the issue in favour of that one.

Thanks for the hard work!

**Pull request closed without merging**
