### PR TITLE
Add next prev button in Docs-->Overview

### PR DESCRIPTION
**Pull request by RonakSurana-2001**
**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #___ 
-  Related to #1072 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**
 I have created this PR to just verify that am I going in correct direction of solving the issue. Is this the thing that you wanted?

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
@RonakSurana-2001 pls. resolve the failing workflows

**Comment by RonakSurana-2001** [comment]
Maintainers can you please check now

**Comment by DhairyaMajmudar** [comment]
@RonakSurana-2001 few points which I noticed to be done for much improved UI

1. Change component name `NextPrevButton.tsx` -> `NavigationButtons.tsx`

1. No need for `code of conduct` Button at `What is JSON Schema?` page 

image

2. Add Prev and Next buttons to `JSON Schema Organizational Code of Conduct` page.

3. Add some more margin-top to buttons... this separates them from text/content above.

4. Add navigation buttons other sections of website too (Getting Started, Reference, Specification)

**Comment by RonakSurana-2001** [comment]
Thanks for suggestions. Will try to complete asap.

**Review by benjagm — CHANGES_REQUESTED** [review]
Great job with this first iteration!

For now just implemented it for the overview section but we need to do it for all the sections: "getting started", "reference" and "specification".

Some additional comments:
 * We need to add the component in the Code of Conduct TSX page.
 * In the first page of the first section, the previous button won't do nothing. The target link is the same, the first page of the first section. Overview/What is JSON Schema.
 * In the last page of each section the next button jumps to the first page of the next section. For example, in Code of Conduct, the next button will be overview page in Getting Started.
 * In the last page of the last section, the next button will jump to the beginning, first page of first section : Overview/What is JSON Schema.
 
 Great progress!!

**Comment by RonakSurana-2001** [comment]
Yes I will submit a PR by end of date.
Actually I am not getting time these days due to job but will do asap 
Hope you will understand

**Comment by RonakSurana-2001** [comment]
I have Made the required changes that you wanted in Docs-->Overview Kindly see

**Comment by RonakSurana-2001** [comment]
I have added to Getting Started-->Examples please review that Also.

**Comment by benjagm** [comment]
Hi @RonakSurana-2001 .

The buttons looks great in the overview section but we need more work to complete it in Getting Started. Let's not add the buttons in Reference and Specification for now so that we can merge this as soon as possible when it is complete.

I recorded a quick video with me feedback. Hopefully this will help with the changes.

https://github.com/user-attachments/assets/d031b408-53e0-4937-ba05-063db3b2488f

Please let me know your thoughts.

**Comment by RonakSurana-2001** [comment]
Thank you @benjagm for a review.
I will soon implement the changes that you suggested in the video.

**Review by benjagm — APPROVED** [review]
Great work on this!

**Pull request merged**
