### PR TITLE
Added new custom tags tip, warning and danger

### PR DESCRIPTION
**Pull request by divyaxdv**
**GitHub Issue:** #239 
Resolves: #239 

**Summary**:

In this PR, I have added new custom tags namely Tip, Warning and Danger

image

image

image

image

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

### CODE REVIEW

**Comment by divyaxdv** [comment]
@benjagm Please review and let me know if any other changes required.

**Comment by gregsdennis** [comment]
Do these always need the title tab, e.g. the "Draft specific info"?  Potentially we want to be able to omit that.

**Comment by divyaxdv** [comment]
It is already optional, if we dont pass the label prop it will be automatically omited.

**Comment by gregsdennis** [comment]
What's the markdown syntax for these?  For example, if I want to use this in a blog post, how do I do that?

**Comment by Relequestual** [comment]
> What's the markdown syntax for these? For example, if I want to use this in a blog post, how do I do that?

Looks like you can use the component name as HTML in the markdown. I believe the main site content and the blog posts are processed the same from markdown.

https://github.com/json-schema-org/website/blob/350b9976d3a233b3b33f32fcff877af8f8991543/pages/understanding-json-schema/basics.md?plain=1#L122-L127

**Comment by benjagm** [comment]
> Looks like you can use the component name as HTML in the markdown

That is right Ben. We have a set of those custom HTML tags and the intend of this issue is to create some more. 
I think we need those tags to be documented. I'll create an issue for it.

**Comment by gregsdennis** [comment]
@Relequestual that example helps, but it only shows a label.  How is this new config value specified?  I don't see that.  Examples of usage would be great.

**Comment by Relequestual** [comment]
> @Relequestual that example helps, but it only shows a label. How is this new config value specified? I don't see that. Examples of usage would be great. - @gregsdennis 

Assuming that by "config value", you're assuming that you pass an attribute to specify the type of box being used, you'd be incorrect in that assumption, although reasonable.

In the opening comment, they said they have added the tags Tip, Warning, and Danger. Literally, you can now use those as HTML tags in the markdown which will be converted to the component during compliation.

Want to use a "Tip" box, use the HTML tag `<Tip></Tip>`, and everything else is the same as the example above.

I know the code could be refactored to reduce duplication, but it does the job.

@divyaxdv Did you want to have a go at refactoring this to reduce duplication? You'd want to do something similar as in [this article](https://www.pawelcebula.com/posts/abstraction-and-composition-in-react-functional-components/) I think.

**Comment by divyaxdv** [comment]
Sure, I will update it.

**Comment by divyaxdv** [comment]
I have created an Information component and is refactoring new tags using it . I have passed the imgSrc and bgcolor prop but for some reason bgcolor prop is not updating colors for tip, warning and danger. I have inspected the elements to check classname and they are fine but still colors are not getting updated. @Relequestual @gregsdennis @benjagm .
I have tried a few things and looking into it, but any kind of help is much appreciated.

**Comment by benjagm** [comment]
> help is much appreciated.

You have done an amazing job @divyaxdv!! Huge thanks! I just pushed some changes to fix the issues with colours. I needed to try different things and finally I fixed it. I also added some other changes.

Please, help let me know if now the issue is fixed.

**Comment by divyaxdv** [comment]
Thanks! @benjagm for your time and help.
image

But I still dont see the colors being updated for tip, danger and warning as mentioned.

**Comment by benjagm** [comment]
> But I still dont see the colors being updated

Are you sure you are testing the code I pushed?

Screenshot 2024-02-22 at 10 54 25

**Comment by gregsdennis** [comment]
I'm not currently set up to run the site.

**Comment by benjagm** [comment]
> Hello @gregsdennis @Relequestual when you get a chance can you also kindly check on your local if the latest changes are working as expected.

You where right, that version was not working as expected. I am pushing another version adding all the code inside StyledMarkdown and not using the Information component, and this seems to work. The previous solution was cleaner but for any reason the styles didn't work.

**Comment by divyaxdv** [comment]
This totally works, but I am still trying figure how it can be still done using the component(information). Thanks! @benjagm

**Comment by gregsdennis** [comment]
> Until then I think we should merge this PR and it could be refactored later if we find a better solution.

My concern with this is that if we merge now and new content is written that uses these features, when we refactor, we'll have to either remember to go everywhere and update the content or we'll have to refactor in a backwards compatible way.

If we're happy to do that, sure, but we need to be aware that this is an outcome of merging now.

**Comment by divyaxdv** [comment]
The way we are trying to refactor will not effect the usage of these tags. Newer content will also use only the label props and other props like color and the icon, that is our design choice so these props will not be exposed for the users to change which will keep the usage consistent throughout the app even though we refactor.  @gregsdennis 

What are your view ? @benjagm

**Comment by benjagm** [comment]
@gregsdennis @divyaxdv I think it is ok to merge this. The tagging will be the same with indepence of the implementation we choose. What I tink is worth is create a md file with the annotations we can use when writing markdown.

**Pull request merged**
