### PR TITLE
feat:ambassadors Page

### LINKED ISSUE #884: ✨ Enhancement: Ambassadors Program page
We need to create a dedicated page for the [JSON Schema Ambassadors program](https://github.com/json-schema-org/community/tree/main/programs/ambassadors). This page will serve as a hub for information about the program, including how to apply and what the program entails and of course list the ambassadors.  In addition to the main page, we'll provide a second page to show the details and contributions of each ambassador.

Below are the detailed requirements based on the provided [prototype](#prototype).

### Requirements

1. **Header Section:**
   - Title: "Become a JSON Schema Ambassador"
   - Short description: "The JSON Schema Ambassadors Program recognizes the people who drive adoption, innovation, and knowledge sharing in the JSON Schema community."
   
2. **Buttons:**
   - "Become Ambassador" button: Should be prominent, leading to an application form and connect with this link: https://github.com/json-schema-org/community/tree/main/programs/ambassadors#become-an-json-schema-ambassador
   - "Learn More" button: This should link to a section or page with more details about the program. This is the link to use: https://github.com/json-schema-org/community/tree/main/programs/ambassadors

3. **Content Sections:**

There should be multiple sections:
- Section 1 : Same card used in the Community page presenting the program.
- Section 2: Types of contributions: "Articles", "Talk", "JSON Schema Adopter", "Case study", "Video", "Book", "Technical Paper", "Initiative or Project", "Working group", "Community"
- Section 3: Ambassadors listing using the data provided here: https://github.com/json-schema-org/community/blob/main/programs/ambassadors/ambassadors.json
-Section 4: Final call to action to join the program.

### Technical Requirements

* Please make sure to use the Card component for generic Cards. For the ambassadors card feel free to create a new component.
* We have multiple pages reading json and rendering it using the card component, like the case studies, use cases or overview pages, make sure you follow a similar approach.
* The ambassadors json is available through github submodules. Just update the community submodule to get current version.

### Ambassador's details.

When clicking on one ambassador we can have a second page showing the Ambassador's contribution like Async API is doing. For reference: https://www.asyncapi.com/community/ambassadors/raphaeldelio

### Prototype:
<div id=prototype></>
Please check this prototype for reference of the main page layout.

[Ambassadors.pdf](https://github.com/user-attachments/files/16735998/Ambassadors.pdf)

Ambassadors-1

### References:
We took inspiration from the AsyncAPI Ambassadors page:
* https://www.asyncapi.com/community/ambassadors
* https://www.asyncapi.com/community/ambassadors/raphaeldelio

### PR DESCRIPTION
**Pull request by Pavankumar07s**
#884 

**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #884
-  Related to #___ 
-  Others? 

**Screenshots/videos:**
Already shared.

https://github.com/user-attachments/assets/27d47dc6-8cd0-48bd-9884-a17db6a78a7c

**If relevant, did you update the documentation?**

Ambassadors page completed.

**Summary**

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Comment by lattaai6** [comment]
Hello, I tried to fix the issue.

This is what I did:

This change adds a new Ambassadors page to the JSON Schema website, accessible via the Community dropdown in the main navigation. The page showcases JSON Schema Ambassadors and their contributions to the community.

You can review changes in this commit: https://github.com/lattaai6/json-schema-org-website-1108/commit/b49ae467913912248e766212f5dd916edf486c26.


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This issue was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by Pavankumar07s** [comment]
Hii @DhairyaMajmudar yes, i am looking on it .Thankyou.

**Comment by Pavankumar07s** [comment]
Hey @DhairyaMajmudar now its look good.Really you are such a great help.Thankyou.

**Review by benjagm — APPROVED** [review]
Great work with this @Pavankumar07s !! There was a lot of great code here. 

I just replaced some texts, some illustrations and fixed some problems with CSS and tailwind. Now it is ready to go.

**Comment by Pavankumar07s** [comment]
@benjagm Thankyou 😊

**Pull request merged**
