### PR TITLE
docs: Change feedback form to actionable questions

### LINKED ISSUE #805: [📝 Docs]: Change feedback form to actionable questions
### What Docs changes are you proposing?

Instead of asking readers if the docs were helpful and allowing writing more details, which is sometimes filled with ambiguous statements, we need to ask questions that give us unambiguous, actionable information. Based on his research on readers' expectations from documentation, Yoel Strimling concludes the most important aspects for readers is that documentation is:
- Easy to find
- Accurate
- Relevant
- Easy to understand

Based on this observation, Strimling recommends to ask four Yes or No questions to retrieve actionable feedback:
- Could you find what you were looking for?
- Was it accurate?
- Was it relevant?
- Was it easy to understand? 

Screen Shot 2024-07-18 at 11 24 37

This proposal therefore suggests replacing the open-ended question *Was this helpful?* with the above questions. It leaves the opportunity to create an issue in case the problem our readers encounter is not covered by these questions.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by harshsbhat**
**What kind of change does this PR introduce?**

Improves the feedback form by adding actionable responses with options YES and NO rather than asking for a descriptive feedback.

**Issue Number:**

-  Closes #805

**Screenshots/videos:**

image

**Summary**

### CODE REVIEW

**Comment by DarhkVoyd** [comment]
Hi @harshsbhat . The CI/CD workflow failed here: https://github.com/json-schema-org/website/actions/runs/10218752435/job/28275614951?pr=841
Can you please check it?

**Comment by DarhkVoyd** [comment]
Also, the linked issue is tagged `GSoD`, so most probably it's part of an existing project board plan/epic. Please ensure that the work to be done is agreed upon and you are assigned the issue/ you have checked with the web team to work on an issue before creating a PR, as mentioned [here](
https://github.com/json-schema-org/website/issues/805#issuecomment-2251457232)

**Comment by harshsbhat** [comment]
I am not very sure what is causing that error. Can you help me? I don't think it is from the file that I have edited

**Comment by harshsbhat** [comment]
> Also, the linked issue is tagged `GSoD`, so most probably it's part of an existing project board plan/epic. Please ensure that the work to be done is agreed upon and you are assigned the issue/ you have checked with the web team to work on an issue before creating a PR, as mentioned [here](
> https://github.com/json-schema-org/website/issues/805#issuecomment-2251457232)

Okay my bad. I won't start to work on something again without the APPROVAL/ASSIGNMENT for the same. So you want me to keep this PR or archive it?

**Comment by harshsbhat** [comment]
> > Also, the linked issue is tagged `GSoD`, so most probably it's part of an existing project board plan/epic. Please ensure that the work to be done is agreed upon and you are assigned the issue/ you have checked with the web team to work on an issue before creating a PR, as mentioned [here](
> > https://github.com/json-schema-org/website/issues/805#issuecomment-2251457232)
> 
> Okay my bad. I won't start to work on something again without the APPROVAL/ASSIGNMENT for the same. So you want me to keep this PR or archive it? 

@DarhkVoyd

**Comment by DarhkVoyd** [comment]
> > Also, the linked issue is tagged `GSoD`, so most probably it's part of an existing project board plan/epic. Please ensure that the work to be done is agreed upon and you are assigned the issue/ you have checked with the web team to work on an issue before creating a PR, as mentioned [here](https://github.com/json-schema-org/website/issues/805#issuecomment-2251457232)
> 
> Okay my bad. I won't start to work on something again without the APPROVAL/ASSIGNMENT for the same. So you want me to keep this PR or archive it?

No worries, Harsh. Let's keep this PR for now. Someone from the web team will review it and provide guidance on how to proceed.

**Comment by aialok** [comment]
> I am not very sure what is causing that error. Can you help me? I don't think it is from the file that I have edited

Basically, the Codecov coverage token is not set up correctly, which is causing the job to fail. You don't need to do anything; the error is in the workflow configuration itself.

**Comment by harshsbhat** [comment]
> > I am not very sure what is causing that error. Can you help me? I don't think it is from the file that I have edited
> 
> Basically, the Codecov coverage token is not set up correctly, which is causing the job to fail. You don't need to do anything; the error is in the workflow configuration itself.
> 

Thanks a lot Alok for helping me out!

**Review by gregsdennis — CHANGES_REQUESTED** [review]
As mentioned in the issue you grabbed this work from, this change needs to incorporate #762, but it doesn't appear to.

The thing is, we haven't made a decision on the direction for both of these issues together.  We need to finalize that decision before work should be done.

To be specific, I don't think it's clear that "submit feedback" means they won't/can't be contacted about their feedback, while "create issue" means "I want to continue this conversation"/"I want more help".

**Comment by benjagm** [comment]
Hi everyone. After losing the Postman accounts we have lost access to the airtable used to store the data. Moving forward we decided to use google sheets instead and we still need to implement the change. Can we hold this change until we are able to store the data again?

**Comment by benjagm** [comment]
@harshsbhat still available to work on this issue? We finally fixed the current feedback component to store data again so we can resume the work here and continue with the changes suggested on #762 . Happy to have a chat and work together on this.

**Comment by harshsbhat** [comment]
yeah sure. I will take a look at this tomorrow and ask some doubts if any. 😊

**Comment by DhairyaMajmudar** [comment]
Hi, @harshsbhat it seems like tests are failing and some merge conflicts are there can you pls. fix them

**Comment by benjagm** [comment]
Thanks for this contribution @harshsbhat . We are going to close this PR as there was no activity in the last 2 months.

**Pull request closed without merging**
