### PR TITLE
Header size reduced when outside landing page.

### LINKED ISSUE #52: Shrink version of the header menu when outside the landing page
Can we shrink the header  it as much as possible when viewing pages that are not the landing page?

### PR DESCRIPTION
**Pull request by deveshidwivedi**
**GitHub Issue:** #52
Resolves #52 

**Summary**:
The header now is reduced in size for all the pages except the landing page, as mentioned in the issue. 

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

### CODE REVIEW

**Review by DhairyaMajmudar — COMMENTED** [review]
Please resolve the failing lint checks you can know more about the reason of failing in its details section.

**Comment by aialok** [comment]
Just want to cross-check from your side: Is the Husky pre-commit hook working when you try to commit? Because if it's working then you will get error there only.
I've noticed that most contributors are encountering test failures in the CI.

Thank you : )

**Comment by benjagm** [comment]
There are still some formatting errors that requires some additional changes:

See : https://github.com/json-schema-org/website/actions/runs/8171033159/job/22338415619?pr=471

**Review by benjagm — CHANGES_REQUESTED** [review]
There are still some formatting errors that requires some additional changes:

See : https://github.com/json-schema-org/website/actions/runs/8171033159/job/22338415619?pr=471

You can use prettier to fix this automatically running:

````
npx prettier --write path-of-the-file-to-format
````

**Comment by lalitkumawat1m** [comment]
@deveshidwivedi are you facing any issue in fixing linting error ?

**Comment by benjagm** [comment]
Closed as we are not receiving any response on this.

**Pull request closed without merging**
