### PR TITLE
Add json-schema-to-ts to implementations

### PR DESCRIPTION
**Pull request by ThomasAribart**
**GitHub Issue:** # / NA

**Summary**:
Add [`json-schema-to-ts`](https://github.com/ThomasAribart/json-schema-to-ts) to the list of implementations.

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

### CODE REVIEW

**Review by benjagm — APPROVED** [review]
Looks good to me.

Thanks a lot for adding your implementation! It is great to have more Typescript tooling!

**Comment by ThomasAribart** [comment]
@benjagm I do not have write access so I can't merge the PR. Can you do it? Thx

**Comment by benjagm** [comment]
Merged. Thanks a lot for adding your implementation @ThomasAribart 🙌🙌

We'll promote this in social media by tomorrow.

**Comment by benjagm** [comment]
We just promoted it in social media: 
 - https://www.linkedin.com/feed/update/urn:li:activity:7150770916728205312
 - https://x.com/jsonschema/status/1745004988579848299?s=20

**Pull request merged**
