### PR TITLE
Feat: Add the Newsletter feature to the website. 

### PR DESCRIPTION
**Pull request by ayushnau**
**GitHub Issue:** #243 

**Summary**:

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**
No

No

### CODE REVIEW

**Review by DhairyaMajmudar — COMMENTED** [review]
Can you pls. resolve the failing lint checks.  The suggestions below will be helpful for that : )

**Comment by ayushnau** [comment]
image
@DhairyaMajmudar not able to do that i am getting this

**Comment by DhairyaMajmudar** [comment]
If you are using node version > 20 degrade it using with the help of node version manager , and then retry.

**Comment by ayushnau** [comment]
@DhairyaMajmudar @benjagm done please check.

**Comment by benjagm** [comment]
Thanks a lot for moving this pr to the new branch! Found 2 small things:

1 We lost this change to add the form to the landing page:
307002914-af07d91e-0b04-4863-85b2-fb61c0741743

2 After the changes added to the footer we'll need to reduce the vertical padding to make sure we show the footer.
Screenshot 2024-03-11 at 13 34 59

**Review by benjagm — CHANGES_REQUESTED** [review]
Left 2 comments [here](https://github.com/json-schema-org/website/pull/489#issuecomment-1988341779).

Thanks a lot!!

**Comment by benjagm** [comment]
Awesome job here !!! I pushed some changes to make sure it merges well into the dev branch!! Excellent!

**Review by benjagm — APPROVED** [review]

**Pull request merged**
