### PR TITLE
added roadmap page

### PR DESCRIPTION
**Pull request by Akshaybagai52**
**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #___ 
-  Related to #___ 
-  Others? 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Review by benjagm — CHANGES_REQUESTED** [review]
Hi @Akshaybagai52 this is a static page but we are looking for dynamic way to read the roadmap issues and its metadata and render them.

**Comment by Akshaybagai52** [comment]
> Hi @Akshaybagai52 this is a static page but we are looking for dynamic way to read the roadmap issues and its metadata and render them.

Is the data hosted on server or any url from where I can find the metadata?

**Comment by benjagm** [comment]
> > Hi @Akshaybagai52 this is a static page but we are looking for dynamic way to read the roadmap issues and its metadata and render them.
> 
> Is the data hosted on server or any url from where I can find the metadata?

Check this comment please: https://github.com/json-schema-org/website/issues/181#issuecomment-2077015787

**Comment by Akshaybagai52** [comment]
> > > Hi @Akshaybagai52 this is a static page but we are looking for dynamic way to read the roadmap issues and its metadata and render them.
> > 
> > 
> > Is the data hosted on server or any url from where I can find the metadata?
> 
> Check this comment please: [#181 (comment)](https://github.com/json-schema-org/website/issues/181#issuecomment-2077015787)

Let me check

**Pull request closed without merging**
