### PR TITLE
Feat: Rebuilding getting started component (#687)

### LINKED ISSUE #549: ✨ Enhancement: Rebuild the getting started guide
### Is your feature request related to a problem? Please describe

We are aware that learning JSON Schema is not easy and we also know that our docs needs a lot of improvement. But now, with the new feedback component we are even more clear about the areas that needs improvement and the getting started guide is clearly one of them.

After long consideration, I think the best approach is proceeding with a first iteration consisting on changing the section [Validating JSON data against the schema](https://json-schema.org/learn/getting-started-step-by-step#validate).

We don't maintain or promote any validator over others and in addition we are not integrating any validator. This is great to keep our neutrality but it adds friction into new users journey. We are going to keep that neutrality but it will be great to allow the users feel the HAHA moment of getting a json message validated against a schema.

My proposal is to create a component that provides different valid and invalid examples for different uses cases following this prototype:

Screenshot 2024-04-18 at 15 51 05

The default example shown by the component is the one used for getting started. Considering that the examples are pre-recorded and we know the validation result. 

1. Initially the component shows the default schema instance.  (this will be paremetrized in a yaml file)
2. The user can select 2 or 3 different instances, valid and invalid and we show the result and the explanation why showing a green check when is valid and red cross when is invalid.
3. We'll provide some other schema examples with instances so the users can see it working in different scenarios. We add simple and other more complex examples.
4. We provide a download button to allow to download the schema and the selected instance so the user can try it with the validator of their choice.

The idea is let the users see the power of the json schema validation and show other real life examples to inspire them.

### PR DESCRIPTION
**Pull request by benjagm**
**What kind of change does this PR introduce?**

Rebuilding getting started guide

**Issue Number:**

-  Closes #549 

**Screenshots/videos:**
N/A

**If relevant, did you update the documentation?**
N/A

**Summary**
Getting stated guide added. 

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by benjagm** [comment]
The new validation components of the getting started guide con tested here:

https://web-new-getting-started.website-2v2.pages.dev/learn/getting-started-step-by-step#validate-json-data-against-the-schema

**Comment by DhairyaMajmudar** [comment]
I have added the download button which on click downloads the schema FIle data

**Comment by benjagm** [comment]
Hi Dhairya. Can you please fix the conflict and make sure that the download button downloads schema and instance in a zip file with the original names?

**Review by benjagm — COMMENTED** [review]
Great job @DhairyaMajmudar. Let's merge this!

**Pull request merged**
