### PR TITLE
Improving Sponsors area 

### LINKED ISSUE #602: ✨ Enhancement: Improve the sponsors area of the landing page
### Is your feature request related to a problem? Please describe

It will be a good idea to improve the sponsors area of the landing page to differentiate each sponsorship layer and also adding buttons to become a sponsor.

I have created this low-fi prototype for inspiration:
Untitled presentation (15)

### Describe the solution you'd like

Please see the prototype provided before.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Are you working on this?

No

### PR DESCRIPTION
**Pull request by Sahil-Shadwal**
**What kind of change does this PR introduce?**
Improving the sponsors area of the landing page to differentiate each sponsorship layer and also adding buttons to become a sponsor.

**Issue Number:**

-  Closes #602 

**Screenshots/videos:**
image

**If relevant, did you update the documentation?**

**Summary**
This enhancement introduces new design for the SPONSORS section of the page, that differentiated sponsors in GOLD, SILVER and BRONZE category . It also introduces an button :-
"Add your logo here " 

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by VivekJaiswal18** [comment]
@Sahil-Shadwal i think only having one button for `add your logo here` would be fine

**Comment by Sahil-Shadwal** [comment]
> @Sahil-Shadwal i think only having one button for `add your logo here` would be fine

Check the issue @VivekJaiswal18

**Review by benjagm — APPROVED** [review]
Great job Sahil!! I just pushed some changes to slightly refine the button's style. Thanks!!

**Comment by Sahil-Shadwal** [comment]
sure thing glad you like it :)

**Pull request merged**
