### PR TITLE
Fixed the side bar of blog post page.

### PR DESCRIPTION
**Pull request by TamannaVerma99**
**What kind of change does this PR introduce?**
A bugfix

**Issue Number:**
#458 
Closes: #458 

**Summary**
Made CSS changes to the left container on blog post page to improve its appearance on scrolling the blog.

**Does this PR introduce a breaking change?**
NO

### CODE REVIEW

**Review by DhairyaMajmudar — APPROVED** [review]
LGTM : )

**Comment by TamannaVerma99** [comment]
> LGTM : )

Thanks!!

**Comment by TamannaVerma99** [comment]
@benjagm Can you please have a look at it. Thanks :)

**Review by benjagm — APPROVED** [review]
Great job! Thanks!

**Pull request merged**
