### PR TITLE
Add support for the Markdown convention for Italic text using _

### PR DESCRIPTION
**Pull request by benjagm**
**GitHub Issue:** # / NA

**Summary**: Currently the text using _ format text as Italic is not working. The expected behaviour of the website is to render _text_ to <i>text</i>.

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

### CODE REVIEW

**Comment by gregsdennis** [comment]
Is this in response to https://github.com/json-schema-org/website/pull/274/files#r1459583392?  I think you have it the other way around.  I'm saying that I use _ and that it works fine.  Juan is saying that * isn't working.

**Comment by jviotti** [comment]
I remember trying `_` too on my post, and that didn't work either. By the look of this patch, I guess its fixing both?

**Comment by benjagm** [comment]
Sorry for merging this too quickly when trying to help you guys with the review of the other blog. This fixes both _ and *.

Thanks and my apologies. @gregsdennis @jviotti

**Comment by jviotti** [comment]
Thanks @benjagm ! I'll try to update my PR with these changes

**Comment by jviotti** [comment]
Works! Thanks!

**Pull request merged**
