### PR TITLE
Feat: Refactoring toc styles

### LINKED ISSUE #784: Table of Contents improvement
Adopt this idea from Heroku table of contents component: 
https://devcenter.heroku.com/articles/heroku-connect-database-tables

With the icon and the sentence "Table of Contents" on top ... I think that improves the experience.

Image

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
**What kind of change does this PR introduce?**
Refactored Table of content styles

**Issue Number:**
-  Closes #784 #795

**Screenshots/videos:**
image

**Summary**
ToC component refactored

### CODE REVIEW

**Review by benjagm — CHANGES_REQUESTED** [review]
We need to add the Table of contents title and the icon as we discussed.

**Review by benjagm — CHANGES_REQUESTED** [review]
We are getting really close. The only thing I found is this error message in the developer mode:
Captura de pantalla 2024-07-17 a las 9 58 04

**Comment by DhairyaMajmudar** [comment]
> We are getting really close. The only thing I found is this error message in the developer mode: Captura de pantalla 2024-07-17 a las 9 58 04

A similar kind of bug is fixed in this pr https://github.com/json-schema-org/website/pull/763
Let me find a fix for this : )

**Review by benjagm — APPROVED** [review]
Awesome work! Let's merge. the circle on top of the vertical line is sometimes not in the exact middle but this is fine for now.

**Pull request merged**
