### PR TITLE
fix: link-redirect-fix

### PR DESCRIPTION
**Pull request by Yashwanth1906**
**What kind of change does this PR introduce?**

- Change to correct wrong redirecting URLs

**Issue Number:**
- Closes #1308

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**

This pull request addresses an issue related to incorrect URL redirection in the JSON Schema website. Users were being redirected to incorrect or unintended pages when clicking on certain links.

### Changes Made:
1. **Corrected Redirecting URLs**: Updated the wrong redirecting URLs in various components to ensure they point to the correct destinations. This change enhances navigation and provides users with access to the intended content.
  
2. **Refactored JSX Components**: Adjusted the formatting of JSX components to comply with the project's style guide. Specifically, I ensured that there were proper spaces before closing brackets in the JSX tags, addressing the errors raised by the reviewers.

3. **Code Consistency**: Ensured consistency in the codebase by adhering to Prettier and ESLint rules, which included correcting formatting issues to enhance code readability and maintainability.

These changes improve user experience by ensuring that links function correctly, reducing frustration caused by misdirected navigation. 

**Does this PR introduce a breaking change?**

- No

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
@Yashwanth1906 run the command `yarn run lint` to fix  the failing ci

**Comment by Yashwanth1906** [comment]
All the corrections done @DhairyaMajmudar

**Comment by DhairyaMajmudar** [comment]
@Yashwanth1906 it seems like there were some complications with the PR since your forked repo is 11 commits behind,
Pls. sync your repo, with the latest commit, create a new branch, and open a PR again.

Feel free to ask on[ JSON Schema slack](https://json-schema.slack.com/ssb/redirect) if you face any difficulty in doing so...

**Comment by Yashwanth1906** [comment]
@DhairyaMajmudar Ok I will submitting the PR soon

**Pull request closed without merging**
