### PR TITLE
fix: spacing between buttons 

### PR DESCRIPTION
**Pull request by Akshaybagai52**
**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #___ https://github.com/json-schema-org/website/issues/535
-  Related to #___ 
-  Others? 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Review by DhairyaMajmudar — APPROVED** [review]
LGTM 🚀

**Review by benjagm — CHANGES_REQUESTED** [review]
Nice job. What you did works perfectly.

I just found un scenario where the all the buttons (search, theme and menu) are not in the best position because the right padding seems too much. The right padding of the menu icon should be the same than top and bottom. See image.

Screenshot 2024-03-22 at 14 08 16

I know this was not part of the issue but it is a great opportunity to fix it.

**Comment by Akshaybagai52** [comment]
> Nice job. What you did works perfectly.
> 
> I just found un scenario where the all the buttons (search, theme and menu) are not in the best position because the right padding seems too much. The right padding of the menu icon should be the same than top and bottom. See image.
> 
> Screenshot 2024-03-22 at 14 08 16
> 
> I know this was not part of the issue but it is a great opportunity to fix it.

I've fixed that can you check now

**Comment by benjagm** [comment]
Thanks. That worked! However I found another scenario for Galaxy Fold (280x653):

Screenshot 2024-03-24 at 10 43 02

**Comment by Akshaybagai52** [comment]
> Thanks. That worked! However I found another scenario for Galaxy Fold (280x653):
> 
> Screenshot 2024-03-24 at 10 43 02

I've fix that can you review now
Thanks

**Review by benjagm — APPROVED** [review]
Looks great! Thanks for this!

**Pull request merged**
