### PR TITLE
Fix: Fixing search bar in responsive screens.

### LINKED ISSUE #345: Search button is not as expected in responsive mode.
#### Describe the bug

In the tablet and mobile view, the search button is not as expected which needed to be corrected.

#### How to Reproduce

1. Open the JSON Schema website 
2. Use developer tools access the tablet and mobile view 

**Screenshots**

- Tablet
Screenshot from 2024-02-23 23-47-31

- Mobile 
Screenshot from 2024-02-23 23-47-18

#### Expected behavior

The search button must be the same as in the desktop view.

### LINKED ISSUE #355: Button alignment in landing page is inconsistent.
#### Describe the bug
The button text is not aligned properly in the page. Centering them will make them more visually appealing. 

#### How to Reproduce
Landing page: https://json-schema.org/

before

https://github.com/json-schema-org/website

pages/index.page.tsx

#### Expected behavior
The button text is not aligned properly in the page. Centering them will make them more visually appealing.

### LINKED ISSUE #374: box shadow when the hamburger menu in mobile design is open
#### Reason/Context

We need this improvement for better user experience 

#### Description

go to this url :-https://json-schema.org/ and turn on mobile responsive 
then you can see there is drop shadow on navbar when it is not open so it is looking good
Screenshot 2024-02-27 at 10 02 40 AM

but when the navbar is open on clicking of hamburger menu then the box shadow removed and it is merging with the white background of the content as can be seen in the screenshot
Screenshot 2024-02-27 at 10 04 06 AM

so there is no separation between navbar and content.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes/No
[JUSTIFICATION]

I would love to work on this issue

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
**GitHub Issue:** #345 #355 #374
Fixes #345
Fixes #355
Fixes #374 

**Summary**: fixed the search bar in responsive mode.

**Changes Done**: 
1. Reduced width of the div.
2. Made div display inline in responsive mode. 
3. Reduced the gap between search icon and text 
4. Added the shadow for fixing issue 374
5. incorporated changes for the issue 355

**Files Changed**
1. `components/Layout.tsx`
2. `pages/index.page.tsx`
6. `styles/globals.css`
### Screenshots

**Before**
Screenshot from 2024-02-25 19-15-46

**After**
image

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
@benjagm pls. have a look : )

**Comment by benjagm** [comment]
Nice job @DhairyaMajmudar !

It worked for all cases but one: Ipad Mini resolutions:

Screenshot 2024-02-26 at 15 19 55

**Review by benjagm — CHANGES_REQUESTED** [review]
Nice job @DhairyaMajmudar !

It worked for all cases but one: Ipad Mini resolutions:

**Comment by DhairyaMajmudar** [comment]
Thanks for testing , I will improve the iPad one and update my pr 😃

**Comment by DhairyaMajmudar** [comment]
@benjagm I have made the changes for iPad mini and also incorporated the changes from  PR #358.

**Comment by benjagm** [comment]
> I have made the changes for iPad mini and also incorporated the changes from PR #358

Can you please #355 as well. Thanks

**Comment by benjagm** [comment]
You did amazing here incorporating all the request @DhairyaMajmudar. Congrats!!!

Now that we are fixing this section of the landing let's make the last change in the seach button to make the the lens icon appear closer to the Search text so we leave this PERFECT. Please see the image below.

Screenshot 2024-02-26 at 20 31 03

What do you think about making this last change?

**Comment by DhairyaMajmudar** [comment]
Thank you for your appreciation @benjagm : )

I think the changes you are suggesting are good making icons and text close to each other is a good idea 👍🏻

**Comment by benjagm** [comment]
@Mvishal123 I am adding you as reviewer of this PR considering we are adding some of your changes for #355

**Comment by DhairyaMajmudar** [comment]
@benjagm I have made the suggested changes.

image

**Comment by DhairyaMajmudar** [comment]
Sure will look into this 👍🏻

**Comment by DhairyaMajmudar** [comment]
@benjagm  I have updated my PR with the suggested changes

image

**Review by benjagm — CHANGES_REQUESTED** [review]
Left 2 small comments in the PR discussion:
https://github.com/json-schema-org/website/pull/359#issuecomment-1969674895

**Comment by DhairyaMajmudar** [comment]
> Left 2 small comments in the PR discussion: [#359 (comment)](https://github.com/json-schema-org/website/pull/359#issuecomment-1969674895)

Thankyou will fix this 👍🏻

**Comment by DhairyaMajmudar** [comment]
@benjagm I have done the suggested fixes pls. have a look

**Review by benjagm — APPROVED** [review]
Looks good to me. Thanks!!

**Pull request merged**
