### PR TITLE
Shrinking header dynamically

### LINKED ISSUE #52: Shrink version of the header menu when outside the landing page
Can we shrink the header  it as much as possible when viewing pages that are not the landing page?

### PR DESCRIPTION
**Pull request by VivekJaiswal18**
**What kind of change does this PR introduce?**
 Feature

**Issue Number:**
-  Closes #52 

**Screenshots/videos:**
Before:
s

After:
image

**If relevant, did you update the documentation?**

No

**Summary**
This PR shrinks the header dynamically when user leaves the landing page.

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by VivekJaiswal18** [comment]
@benjagm No worries I would be happy to solve that. I will raise a new PR for this by today itself. :)

**Comment by benjagm** [comment]
Hi @VivekJaiswal18 . Hi just realised that this issue was assigned to @deveshidwivedi with a PR actually opened. Let's hold this one for now.

**Comment by VivekJaiswal18** [comment]
Okay, but it was showing no assignees that's why I picked it up,

**Comment by benjagm** [comment]
Closed as we decided to not implement this feature.

**Pull request closed without merging**
