### PR TITLE
modify the new-implementation.yml to trigger workflow on first PR

### LINKED ISSUE #755: 🐛 Bug: Modify new-implementation.yml workflow to run only for first time contributors
### Describe the bug

The new-implementation.yml workflow is running for all PRs adding a new tool but It started to be noisy. 

We' like this to run only for implementers adding a tool for the first time.

### Steps To Reproduce

After a new PR to paths:
      - data/*.yml
      - pages/implementations/main.md

### Expected Behavior

Run only first time PRs.

### Screenshots

_No response_

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

### Do you think this work might require an [Architectural Decision Record (ADR)]? (significant or noteworthy)

Yes

### PR DESCRIPTION
**Pull request by nikhilkalburgi**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

-  Closes #755 

**Screenshots/videos:**

**If relevant, did you update the documentation?**

No

**Summary**
This adds an additional condition to the existing check to trigger the action for first time contributors only for th path "data/tooling-data.yml"

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by gregsdennis** [comment]
Why does this have so many changes?!  Isn't this just a workflow edit?

**Comment by DhairyaMajmudar** [comment]
> Why does this have so many changes?! Isn't this just a workflow edit?

The large diff is because of the changes done in yarn.lock file

**Review by DhairyaMajmudar — APPROVED** [review]
LGTM 🚀

**Comment by benjagm** [comment]
Hi @nikhilkalburgi Why you closed this PR?

**Pull request closed without merging**
