### PR TITLE
`CONTRIBUTING`  I have changed line 35 of eslintrc.js based on the issue #313

### PR DESCRIPTION
**Pull request by AymarN**
**What kind of change does this PR introduce?**
The line 35 of eslintrc has been changed.

**826:**

-  Closes #[313 ](https://github.com/json-schema-org/website/issues/313)
-  Related to #[826](https://github.com/json-schema-org/website/issues/826)
-  Others? 

**Screenshots/videos:**
Screenshot -1
Problem -1
Solution - 1

**If relevant, did you update the documentation?**

**Summary**
There is a set up issue on windows once the installation guide is followed. An error is generated:
Expected linebreaks to be 'LF' but found 'CRLF' On Windows.
[313 ](https://github.com/json-schema-org/website/issues/313)
#[826](https://github.com/json-schema-org/website/issues/826)
**Does this PR introduce a breaking change?**

That affects the set up on Unix computers and on Windows.

### CODE REVIEW

**Comment by gregsdennis** [comment]
Why do we think an ADR is required for this?  It seems like such a small thing.

**Comment by AymarN** [comment]
> Why do we think an ADR is required for this? It seems like such a small thing.

I believe the problem was resolved through issue #313 . However it has not been changed in the source code. That affects the set up on Windows and very likely on Unix computers. The line shall be changed so that the lint tests go through along with the cypress tests. Besides, the installation guide may mention that Visual Studio Code is the IDE which matches with the project. Afterwards, if a pull request has an issue associated with it,  it should inherit present ad-required labels.(CONTRIBUTING.md)

**Comment by gregsdennis** [comment]
ADRs are for (generally large and impactful) topics which have been thoroughly discussed and a vote or some other mechanism has been utilized to make a final decision.  The ADR then documents that decision.

I don't think that line terminations in the website code fit that requirement.

---

Why not update CONTRIBUTING as part of this PR?  You're making the change here, we should go ahead and update the instructions to others.  It should also be part of the build so that the build fails if the code's not correct (if it's not doing that already).

**Comment by AymarN** [comment]
> ADRs are for (generally large and impactful) topics which have been thoroughly discussed and a vote or some other mechanism has been utilized to make a final decision. The ADR then documents that decision.
> 
> I don't think that line terminations in the website code fit that requirement.
> 
> Why not update CONTRIBUTING as part of this PR? You're making the change here, we should go ahead and update the instructions to others. It should also be part of the build so that the build fails if the code's not correct (if it's not doing that already).

Thank you for your recommendation. Are there any blockers to merge ?

**Comment by gregsdennis** [comment]
This needs someone more familiar with the build tools than me.  cc: @jdesrosiers / @benjagm

**Review by jdesrosiers — APPROVED** [review]
This looks ok to me.

**Review by aialok — APPROVED** [review]
LGTM :rocket: 

Thank you @AymarN  : )

**Review by benjagm — CHANGES_REQUESTED** [review]
Thanks a lot for putting this together! The change in eslintrc.js looks good,  however all the changes in the getting started examples should be removed from this PR.

**Comment by AymarN** [comment]
> Thanks a lot for putting this together! The change in eslintrc.js looks good, however all the changes in the getting started examples should be removed from this PR.

Thank you. I updated the branch and hoping for your approval.

**Review by benjagm — APPROVED** [review]

**Comment by benjagm** [comment]
Congrats on merging your first Pull Request!!

**Pull request merged**
