### PR TITLE
handled the overflow issue in blog space

### LINKED ISSUE #393: Bug: Overflow in blogs page.
#### Describe the bug

There's an overflow seen in the blogs page of the website, this overflow needs to be removed since it hinders user experience.

#### How to Reproduce

1. Visit the website in production.
2. Navigate to blogs page.

image

#### Expected behavior 
There must be no overflow in the website

### PR DESCRIPTION
**Pull request by Adity20**
**What kind of change does this PR introduce?**
Handle Overflow in Blog Space

**Issue Number:**
-  Closes #393 
-  Related to #393 

**Screenshots/videos:**

**Summary**
This pull request addresses the issue of content overflow in the blog space of our website. The changes ensure that the content within the blog space does not overflow its container, improving the readability and user experience.

### CODE REVIEW

**Comment by Adity20** [comment]
@DhairyaMajmudar @benjagm kindly review this PR for issue #393 and let me know if any more changes are required

**Review by DhairyaMajmudar — APPROVED** [review]

**Comment by DhairyaMajmudar** [comment]
Thanks for the PR , looks good to me 💯

**Comment by Adity20** [comment]
Okay @DhairyaMajmudar :).

**Comment by Adity20** [comment]
@benjagm Kindly review this PR

**Review by benjagm — APPROVED** [review]
Good job thanks!!

**Comment by Adity20** [comment]
Thanks for the constant support throughout @benjagm.

**Pull request merged**
